opensearch-project/dashboards-observability

common/constants/shared.ts, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
Correct ppl learn more link
#153 
=> Correct ppl learn more link

public/components/visualizations/charts/bar/bar.tsx
=> Fix show legend in bar charts

public/components/event_analytics/explorer/explorer.tsx
Fix for visualization rendering not working in app analytics.
=> Few fixes regarding issues for visualization rendering

.cypress/integration/4_trace_analytics_dashboard.spec.js, .cypress/utils/constants.js
Fixes Cypress test for trace analytics to run more consistently and with standard data test subj
=> Fix trace analytics cypress

package.json, yarn.lock
Add debug 3.1.0 to resolutions for fixing CVE issue.
=> [CVE] Fix for debug cve issue

package.json, yarn.lock
Manual backporting CVE fixes for debug dependency.
=> [BACKPORT 2.x] Manual backporting CVE fix

.github/workflows/dashboards-observability-test-and-build-workflow.yml, opensearch_dashboards.json, package.json
=> Bump Version to 2.6

package.json, yarn.lock
=> Upgrade cypress to 6

common/types/custom_panels.ts, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.scss, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.scss, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx, yarn.lock
Update error handling in viz container to show user friendly errors in Panel Visualizations. 
#161 
=> Update error handling in viz container

.cypress/integration/1_event_analytics.spec.js, .cypress/utils/event_analytics/constants.js, common/types/explorer.ts, public/components/common/search/search.tsx, public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap, public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap, public/components/event_analytics/explorer/save_panel/save_panel.tsx, public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx, public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx, public/components/event_analytics/explorer/visualizations/index.tsx, public/components/event_analytics/hooks/use_render_visualizations.ts
Manually backport #220 to 2.x.
=> [BACKPORT] Backport/backport 220 to 2.x

public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/trace_view.tsx
Signed-off-by: Derek Ho <dxho@amazon.com>
#269 
=> quick fix for traces and services indiviudal page

.cypress/integration/4_trace_analytics_dashboard.spec.js, .cypress/integration/5_trace_analytics_services.spec.js, .cypress/integration/6_trace_analytics_traces.spec.js, .cypress/utils/constants.js, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap, public/components/trace_analytics/components/common/filters/filters.tsx, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/mode_picker.test.tsx.snap, public/components/trace_analytics/components/dashboard/mode_picker.tsx, public/components/trace_analytics/components/dashboard/top_groups_page.tsx, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap, public/components/trace_analytics/components/services/services_table.tsx, public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap, public/components/trace_analytics/components/traces/service_breakdown_panel.tsx, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, public/components/trace_analytics/components/traces/span_detail_panel.tsx, public/components/trace_analytics/components/traces/span_detail_table.tsx, public/components/trace_analytics/components/traces/traces_table.tsx, public/components/trace_analytics/home.tsx
fix up cypress and add jaeger tests (#265)
* fix up cypress and add jaeger tests
* fix snapshot tests
* fix services cypress file and add jaeger tests
* fix trace cypress and jaeger for traces
---------
(cherry picked from commit 7daf880d7d7dc8b37befc38356e4a21cdb65fe84)
=> [BACKPORT 2.x] cypress test fixes for jaeger

release-notes/opensearch-observability.release-notes-2.6.0.0.md
=> fix up release notes for 2.6

package.json, release-notes/opensearch-observability.release-notes-2.6.0.0.md
=> [Backport 2.x] move performance now to run time dep (#309) 

common/constants/explorer.ts, public/components/app.tsx, public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_header.test.tsx.snap, public/components/event_analytics/explorer/log_patterns/__tests__/__snapshots__/patterns_table.test.tsx.snap, public/components/event_analytics/explorer/log_patterns/__tests__/patterns_header.test.tsx, public/components/event_analytics/explorer/log_patterns/__tests__/patterns_table.test.tsx, public/components/event_analytics/explorer/log_patterns/log_patterns.tsx, public/components/event_analytics/explorer/log_patterns/patterns_header.tsx, public/components/event_analytics/explorer/log_patterns/patterns_table.tsx, public/components/event_analytics/home/home.tsx, public/components/event_analytics/redux/reducers/fetch_reducers.ts, public/components/event_analytics/redux/slices/count_distribution_slice.ts, public/components/event_analytics/redux/slices/field_slice.ts, public/components/event_analytics/redux/slices/patterns_slice.ts, public/components/event_analytics/redux/slices/query_result_slice.ts, public/components/event_analytics/redux/slices/query_slice.ts, public/components/event_analytics/redux/slices/query_tab_slice.ts, public/components/event_analytics/redux/slices/visualization_slice.ts, public/components/event_analytics/redux/slices/viualization_config_slice.ts, public/components/metrics/redux/slices/metrics_slice.ts, public/components/metrics/sidebar/__tests__/searchbar.test.tsx, public/components/metrics/sidebar/__tests__/sidebar.test.tsx, public/components/metrics/top_menu/__tests__/metrics_export_panel.test.tsx, public/components/metrics/top_menu/__tests__/top_menu.test.tsx, public/components/metrics/view/__tests__/metrics_grid.test.tsx, public/framework/redux/reducers/index.ts, public/framework/redux/store/index.ts
- Use createSelector and connect together
- Log pattern modularization
- Fix all related liniting errors
Just combined redux and log pattern refactoring together in one PR. 
=> [Refactoring] Redux and log pattern related refactoring

public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap, public/components/custom_panels/__tests__/custom_panel_table.test.tsx, public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/home.tsx
Create page for custom panels
#108 
=> Panels create page

public/components/notebooks/components/note_table.tsx, public/components/notebooks/components/notebook.tsx
In preparation for refactoring Notebooks to use SavedObjects, fixing linter errors that will obscure changelist on forthcoming CR.
- [-] New functionality includes testing - no changed functionality
=> Lint Notebook and NotebookTable in preparation for refactoring

.github/workflows/dashboards-observability-test-and-build-workflow.yml, opensearch_dashboards.json, package.json
=> bump version to 2.7

.github/CODEOWNERS, CODEOWNERS, MAINTAINERS.md
=> baseline repo permissions and groups

public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_input.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap
2.x CI is breaking due to old snapshots on notebooks UI
updated the snapshots
=> Update notebooks snapshots

public/components/application_analytics/components/flyout_components/service_detail_flyout.tsx
(cherry picked from commit 9ad2c4d43156dd761387ef37ca3c94234cf2e2b2)
=> bug fix for empty connected services array (#339)

common/types/explorer.ts, public/components/app.tsx, public/components/application_analytics/home.tsx, public/components/common/side_nav.tsx, public/components/custom_panels/home.tsx, public/components/event_analytics/explorer/log_explorer.tsx, public/components/event_analytics/home/home.tsx, public/components/event_analytics/index.tsx, public/components/index.tsx, public/components/notebooks/components/main.tsx, public/plugin.ts
=> Left nav cohesion

public/plugin.ts
ID in edit url is missing object type
=> Fix saved visualization edit url in visualize

public/components/trace_analytics/components/dashboard/dashboard_content.tsx, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/services/services_content.tsx, public/components/trace_analytics/components/traces/trace_view.tsx, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/home.tsx, public/components/trace_analytics/trace_side_nav.tsx
Fix trace Analytics and add side nav for child components
#350 
=> Fix trace analytics navigaiton

public/components/custom_panels/home.tsx
=> fix deleted import

public/components/event_analytics/explorer/log_explorer.tsx, public/components/event_analytics/index.tsx
Fix bug of not able to switch tabs in explorer
=> Fix tab switching bug for event analytics

public/components/trace_analytics/components/common/legacy_route_helpers.ts
=> Fix legacy route for traces

public/components/custom_panels/home.tsx
=> Organize imports on custom panels home file

public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/__tests__/custom_panel_table.test.tsx, public/components/custom_panels/helpers/__tests__/utils.test.tsx, public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap, public/components/event_analytics/explorer/save_panel/__tests__/save_panel.test.tsx, test/setup.jest.ts
=> Update jest tests and snapshots for panels with redux

public/components/notebooks/components/paragraph_components/para_output.tsx, public/services/saved_objects/saved_object_savers/ppl/save_as_new_query.ts, public/services/saved_objects/saved_object_savers/ppl/save_as_new_vis.ts
=> Fix redirection to legacy event_analytics URL

.cypress/integration/2_notebooks.spec.js, public/components/metrics/helpers/utils.tsx, public/components/metrics/top_menu/__tests__/metrics_export_panel.test.tsx, public/components/metrics/top_menu/metrics_export_panel.tsx, public/components/metrics/top_menu/top_menu.tsx
Metrics analytics support for SOpanels 
=> Metrics analytics support for SOpanels 

public/plugin.ts
=> change plugin ordering

.cypress/integration/2_notebooks.spec.js, public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap, public/components/notebooks/components/main.tsx, public/components/notebooks/components/note_table.tsx, public/components/notebooks/components/notebook.tsx
* notebooks fix for cypress and minor bugs
* remove comments
---------
(cherry picked from commit 3219f143515e53e7e9d82ee4ee962adf6d820b4b)
=> [Backport 2.7] notebooks fix for cypress and minor bugs (#392)

public/components/metrics/sidebar/__tests__/__snapshots__/searchbar.test.tsx.snap, public/components/metrics/sidebar/search_bar.tsx, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/metrics/top_menu/top_menu.scss, public/components/metrics/top_menu/top_menu.tsx
Buttons will overflow if on a small screen with nav bar docked, remove unnecessary styles to prevent it
=> Adjust metrics top menu layout to avoid overflow

public/components/custom_panels/helpers/add_visualization_popover.tsx
=> Fix redirection to legacy event_analytics URL from dashboards

public/components/custom_panels/custom_panel_view_so.tsx
I don't understand why there are so many commented code in this file and the difference between `savedVisualizationId` vs. `oldVisualizationId`, @ps48 or @pjfitzgibbons ?
=> Support duplicate visualization in dashboard

release-notes/dashboards-observability.release-notes-2.7.0.0.md
=> Release Notes 2.7.0.0

public/components/custom_panels/helpers/add_visualization_helper.ts, public/components/custom_panels/redux/panel_slice.ts, public/components/metrics/top_menu/top_menu.tsx
Fix saving multiple metrics to SOpanels
* This PR fixes saving multiple metrics issue from metrics analytics to a SavedObject Panel
=> Fix saving multiple metrics to SOpanels

.github/CODEOWNERS, CODEOWNERS, MAINTAINERS.md
Baseline repo maintainers and codeowners
fix: #275 
=> update maintainers and codeowners

public/components/metrics/top_menu/top_menu.tsx
=> Save new prometheus metrics to OSD saved objects

.cypress/integration/3_panels.spec.ts, .cypress/integration/7_app_analytics.spec.js, README.md, public/components/application_analytics/home.tsx, public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/custom_panel_view_so.tsx, public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx, public/components/custom_panels/redux/panel_slice.ts, test/panels_constants.tsx
Observability Dashboards renaming for toast message.
=> Renaming custom panels to Observability Dashboards

public/components/event_analytics/explorer/log_patterns/log_patterns.tsx
=> Open log patterns by default

public/components/event_analytics/explorer/log_patterns/log_patterns.tsx
(cherry picked from commit 72970aa5af30f6ea7c07271375feae67b11d8b6c)
backport #444
=> Open log patterns by default (#444)

.cypress/integration/2_notebooks.spec.js
Fixed all of the testing in notebooks.
Greatly improved speed removing unnecessary waits.
=> Cypress Testing v12.8.1 - Notebooks fully working

.github/workflows/dashboards-observability-test-and-build-workflow.yml, opensearch_dashboards.json, package.json
=> Bump version to 2.8

public/components/trace_analytics/requests/request_handler.ts
Updating trace DSL request handler
#471 
=> Updating trace DSL request handler

.cypress/integration/8_metrics_analytics.spec.js, .cypress/utils/metrics_constants.js, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap, public/components/event_analytics/explorer/save_panel/save_panel.tsx, public/components/metrics/index.tsx, public/components/metrics/redux/slices/metrics_slice.ts, public/components/metrics/sidebar/__tests__/__snapshots__/searchbar.test.tsx.snap, public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/metrics/sidebar/metrics_accordion.tsx, public/components/metrics/sidebar/search_bar.tsx, public/components/metrics/sidebar/sidebar.tsx, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/metrics/top_menu/top_menu.tsx, public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap, public/components/metrics/view/__tests__/metrics_grid.test.tsx, public/components/metrics/view/metrics_grid.tsx
- Added cypress test for metrics
- Fixed a metrics bug where metrics home page won't display custom metrics if there's no prometheus metrics instance started
- Fixed a metrics bug where Add metric, click edit and remove the metric, then add it again, metrics page will be blank
=> Add Metrics cypress and bug fixes

release-notes/opensearch-observability.release-notes-2.8.0.0.md
=> 2.8 release notes

release-notes/dashboards-observability.release-notes-1.3.10.md
=> 1.3.10 Release Notes

.env, DEVELOPER_GUIDE.md, Dockerfile, Using-Docker.md, docker-compose.yml
add capability to build the plugin and add it into the docker of the Opensearch-Dashboard
update the developer-guid to reflect the correct bootstraping process
add docker-compose support and tutorial
- https://github.com/opensearch-project/dashboards-observability/issues/574
=> add docker-compose support 

release-notes/dashboards-observability.release-notes-2.9.0.0.md
=> Release Nodes 2.9.0

release-notes/dashboards-observability.release-notes-2.9.0.0.md
=> Update Release Notes 2.9 w/ Documentation section

public/components/explorer/visualizations/_mixins.scss, public/components/explorer/visualizations/_variables.scss, public/components/explorer/visualizations/app.scss, public/components/explorer/visualizations/config_panel/config_panel.scss, public/components/explorer/visualizations/config_panel/config_panel.tsx, public/components/explorer/visualizations/frame_layout.scss, public/components/explorer/visualizations/frame_layout.tsx, public/components/explorer/visualizations/workspace_panel/workspace_panel_wrapper.scss, public/components/explorer/visualizations/workspace_panel/workspace_panel_wrapper.tsx
Remove unused components and tests.
=> Remove unused components and tests

README.md
update readme to reflect recent changes in the plugins
- https://github.com/opensearch-project/dashboards-observability/issues/690
-
=> update readme to reflect recent changes

.github/ISSUE_TEMPLATE/integration_request.md
Adding an integration suggestion github issue template
=> Add Integration request github issue template

server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.1.json, server/adaptors/integrations/__test__/local_repository.test.ts
=> [BACKPORT] Link fix 2.9

server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.1.json, server/adaptors/integrations/__test__/local_repository.test.ts
=> [BACKPORT] Link fix 2.x

.env, Using-Docker.md, docker-compose.yml
Simplify docker-compose to help user faster adoption and bootstrap
https://github.com/opensearch-project/dashboards-observability/issues/762
=> simplify docker-compose.yml

docker-compose.yml
fix a `docker-compose.yml` dashboard issue with OPENSEARCH_HOSTS
=> fix docker-compose.yml dashboard 

server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
Fixes broken link in Apache integrations
#810 
=> Updated link in sourceURL

public/components/integrations/components/added_integration_overview_page.tsx, public/components/integrations/components/added_integration_table.tsx
Integration deletion currently doesn't register without a refresh, this PR fixes that
Resolves #767 
=> Fix integration removal timing

public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap, public/components/integrations/components/integration_header.tsx
Changes integration description that displays on the integrations page.
#770
=> Modified Integrations Description

README.md
update readme with the integration related docs and screen shorts
=> update readme with the integration related info

public/components/integrations/components/integration.tsx
=> [BACKPORT 2.9] Fix index name collisions on integration sample creation. (#818)

public/components/integrations/components/available_integration_overview_page.tsx
change unapplied cateogry filter to empty instead of x
=> Change unapplied category filter to empty instead of x

server/adaptors/integrations/__data__/repository/aws_cloudtrail/schemas/aws_s3-1.0.0.mapping.json, server/adaptors/integrations/__data__/repository/aws_s3/schemas/aws_s3-1.0.0.mapping.json, server/adaptors/integrations/__data__/repository/aws_vpc_flow/schemas/aws_s3-1.0.0.mapping.json, server/adaptors/integrations/__data__/repository/aws_waf/schemas/aws_s3-1.0.0.mapping.json
consolidate aws_s3-1.0.0.mapping.json schema to match all across
=> consolidate aws_s3  schema  

server/adaptors/integrations/__data__/repository/nginx/schemas/http-1.0.0.mapping.json
consolidate http-1.0.0.mapping.json schema to match all across
=> consolidate http  schema

server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json, server/adaptors/integrations/__data__/repository/aws_elb/schemas/logs_elb-1.0.0.mapping.json, server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json, server/adaptors/integrations/__data__/repository/aws_vpc_flow/info/README.md, server/adaptors/integrations/__data__/repository/aws_vpc_flow/schemas/aws_s3-1.0.0.mapping.json, server/adaptors/integrations/__data__/repository/aws_vpc_flow/schemas/logs_vpc-1.0.0.mapping.json
Due to broken merges and blocked backport PRs, VPC and ELB are both not up to date. This PR just copies the changes over, allowing us to close #834 
=> Backport ELB and VPC changes to 2.9

release-notes/dashboards-observability.release-notes-1.3.12.md
=> Add release notes for 1.3.12

.github/workflows/backport.yml
=> Remove extra backport labels

server/adaptors/integrations/__data__/repository/aws_cloudtrail/schemas/cloud-1.0.0.mapping.json, server/adaptors/integrations/__data__/repository/aws_elb/schemas/cloud-1.0.0.mapping.json, server/adaptors/integrations/__data__/repository/aws_vpc_flow/schemas/cloud-1.0.0.mapping.json
consolidate cloud schema to match all across our integrations 
=> consolidate cloud schema to match all across

.env, DEVELOPER_GUIDE.md, README.md, Using-Docker.md, docker-compose.yml
Update Readme file and add docker-compose file for test purposes for the integration 
=> add docker-compose.yml testing and readme for integration to 2.9

public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap, public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap, public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap, public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
update logo related snapshots due to upstream changes
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4702
=> update logo related snapshots due to upstream changes

release-notes/dashboards-observability.release-notes-2.10.0.0.md
=> Release Notes 2.10

public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/field.test.tsx.snap, public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
=> updated snapshots

common/constants/shared.ts, public/components/datasources/components/manage/data_connection.tsx
Adding redirection to query workbench
#1020 
=> Adding redirection to query workbench

.cypress/integration/8_metrics_analytics.spec.js, public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/metrics/redux/slices/metrics_slice.ts, public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap, public/components/metrics/view/__tests__/metrics_grid.test.tsx, public/components/metrics/view/metrics_grid.tsx, public/components/visualizations/charts/lines/line.tsx, public/components/visualizations/charts/shared/common.ts, test/__mocks__/coreMocks.ts
=> Backport #899 to 2.x branch

common/constants/data_connections.ts, public/components/datasources/components/__tests__/__snapshots__/connection_details.test.tsx.snap, public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_description.test.tsx.snap, public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_table.test.tsx.snap, public/components/datasources/components/data_connections_header.tsx, public/components/datasources/components/manage/access_control_tab.tsx, public/components/datasources/components/manage/connection_management_callout.tsx, public/components/datasources/components/manage/data_connection.tsx, public/components/datasources/components/manage/manage_data_connections_description.tsx, public/components/datasources/components/new/auth_details.tsx, public/components/datasources/components/new/configure_datasource.tsx, public/components/datasources/components/new/configure_prometheus_datasource.tsx, public/components/datasources/components/new/configure_s3_datasource.tsx, public/components/datasources/components/new/new_datasource_card_view.tsx, public/components/datasources/components/new/query_permissions.tsx, public/components/datasources/components/new/review_prometheus_datasource_configuration.tsx, public/components/datasources/components/new/review_s3_datasource_configuration.tsx
=> Data sources copy updates

release-notes/dashboards-observability.release-notes-2.11.0.0.md
=> 2.11 release notes

public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/home/__tests__/__snapshots__/saved_query_table.test.tsx.snap, public/components/event_analytics/home/saved_objects_table.tsx, public/components/event_analytics/index.tsx
This is enable multi select in events home table and also decreased the toast life time for live tail 
=> Fix events home table and toast life time

public/components/event_analytics/explorer/visualizations/config_panel/config_panel.scss
Fixes dark mode config panel
Fixed config panel's dark mode
=> Fixed Visualization Config Panel dark mode

public/components/common/search/sql_search.tsx, public/components/event_analytics/explorer/direct_query_running.tsx, public/components/event_analytics/redux/slices/search_meta_data_slice.ts, public/services/requests/sql.ts, server/adaptors/opensearch_observability_plugin.ts, server/routes/datasources/datasources_router.ts
Support cancellation of async queries
=> Support cancellation of async queries

public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/manage/data_connection.tsx, public/components/datasources/components/manage/manage_data_connections_table.tsx
- Adds back linking from datasources UI to integrations
=> Link integrations from datasources UI

public/components/datasources/components/new/query_permissions.tsx
=> Update empty allowed roles to admin only

opensearch_dashboards.json, package.json
=> version bump

.github/workflows/integration-tests-workflow.yml
Resolving an old todo, in response to [the breaking upstream bootstrap change](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5465) that is causing our [CI to fail bootstrap](https://github.com/opensearch-project/dashboards-observability/actions/runs/6897977875).
Part of longstanding work on #1040 
=> Update node version in integration tests workflow

release-notes/dashboards-observability.release-notes-2.11.1.0.md
=> Updated release notes - no Refactor

release-notes/dashboards-observability.release-notes-2.11.1.0.md
=> Reconciled release notes 2.11.1 with reversal commit

.github/workflows/ftr-e2e-dashboards-observability-test.yml
Add FTR workflow for dashboards observability
=> [CI/CD] Add FTR workflow for dashboards observability

common/constants/explorer.ts
Correct learn more link in log explorer home page.
=> Correct learn more link in log explorer home page

.cypress/integration/integrations_test/integrations.spec.js, .eslintrc.js, public/components/integrations/components/setup_integration.tsx
Re-applies lint fixes that were done in #1331 on main, to keep affected files in sync across branches.
N/A
=> Fix lints for integrations.spec.js and setup_integrations.ts

.github/workflows/ftr-e2e-dashboards-observability-test.yml
Add FTR workflow for dashboards observability
* Backport #1315  
=> [Backport 2.x] Add FTR workflow for dashboards observability

public/components/event_analytics/redux/slices/query_slice.ts
=> Feature explorer query assistant

public/components/common/helpers/ppl_docs/commands/syntax.ts
=> fix syntax error from #1233

common/query_manager/query_parser/ppl_query_parser.ts
adds error handling to stats query parser antlr
https://github.com/opensearch-project/dashboards-observability/issues/1403
=> fix explorer stats function typing crash

package.json, yarn.lock
=> [1.3] upgrade plotly to v2 (#1432)

common/types/data_connections.ts, public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/manage/accelerations_recommendation_callout.tsx, public/components/datasources/components/manage/associated_objects_tab.tsx, public/components/datasources/components/manage/data_connection.tsx
Manual backport of #1470 
* Relate #1470
=> [Backport 2.x] Data sources associated objects tab (#1470)

.cypress/integration/panels_test/panels.spec.ts
Fixes flaky panels Cypress test.
=> Fixing Flaky Panels Test

public/index.ts, public/plugin.tsx, public/types.ts
Export observability startdeps to be used for dependent plugins
Follow-up #1508 
=> Export observability start interface

public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
Core's at it again: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6060
This PR updates the snapshots to fix CI
N/A
=> Update data grid snapshots

common/constants/data_sources.ts, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/utils.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/utils.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/define_index_options.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_advanced_settings.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_type_selector.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/define_index_options.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_setting_options.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_type_selector.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/preview_sql_defintion.tsx
Fix create acceleration bugs
1. Update Continue in SQL workbench butotn
2. Update Index name regex and description
3. Update acceleration type wordings in selector
4. Fix non error state for refresh type change
=> Fix create acceleration bugs

common/constants/data_sources.ts, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration_button.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_setting_options.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_setting_options.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/preview_sql_defintion.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/__tests__/__snapshots__/query_visual_editor.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/group_by_tumble_expression.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/__snapshots__/skipping_index_builder.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/skipping_index_builder.tsx, public/framework/catalog_cache/cache_loader.tsx, public/framework/datasources/direct_query_hook.tsx
Create acceleration flyout bug fixes
* Add error catches for cache loaders
* Add warning toasts when cache is outdated
* Fixes edit in query workbench button
* Fixes "creating acceleration" button in loading state
* Only show the list of acceleration methods that are compatible with the Datatype 
* Update jest tests
=> Create acceleration flyout bug fixes

public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap
Updating snapshot to fix build
N/A
=> Updating snapshot to fix build

server/index.ts
Enable query assist feature by default
N/A
=> Enable query assist by default

opensearch_dashboards.json, public/plugin.tsx, public/types.ts
=> prevent logged out datasources call

server/adaptors/integrations/integrations_builder.ts
There was a test to make sure the whole workflow selection process worked, but I forgot to actually supply the workflow options to the selection method...
N/A
=> Bugfix: Use workflows option in selection

server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_mv_vpc-1.0.0.sql
update mv names to include double "_" to match recent integration infrastructure update
=> update mv name to include double "_"

public/components/datasources/components/manage/access_control_tab.tsx
Signed-off-by: Derek Ho <dxho@amazon.com>
(cherry picked from commit c95b1d789bce04460df26b6a4886d754602f35bb)
Backport #1224 
N/A
=> [Backport 2.x] Change query access messaging (#1224)

release-notes/dashboards-observability.release-notes-2.14.0.0.md
=> 2.14 release notes

common/constants/shared.ts, public/components/visualizations/plotly/plot.tsx
add data-point visualization for metrics analytics 
#1758
https://github.com/opensearch-project/dashboards-observability/assets/48943349/40d483b5-6f9c-4805-890e-530af693cdad
=> Fix metrics single data-point visability

public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap, public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap, public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap, public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/treemap.test.tsx.snap, public/components/visualizations/plotly/__tests__/__snapshots__/plotly.test.tsx.snap
Several broken snapshot chnages from upstream, and a stray integration content directory, are causing several test suites to fail.
N/A
=> Fix all the unit tests

common/constants/data_sources.ts, public/framework/catalog_cache/cache_intercept.test.ts, public/framework/catalog_cache/cache_intercept.ts
Adding test for clear cache on logout
https://github.com/opensearch-project/dashboards-observability/issues/1484
=> Adding test for clear cache on logout

public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap, public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap, public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap, public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/treemap.test.tsx.snap, public/components/visualizations/plotly/__tests__/__snapshots__/plotly.test.tsx.snap
Continuing to chase https://github.com/opensearch-project/dashboards-observability/pull/1786 through all the branches, didn't realize the snapshot issues were due to it
N/A
=> Update snapshots on 2.14

server/adaptors/metrics/metrics_analytics_adaptor.ts
Update metrics analytics queries to match the SS40 metrics schema according to OTEL spec
=> Fix otel queries metrics to match OTEL spec

server/adaptors/integrations/__data__/repository/amazon_cloudfront/amazon_cloudfront-1.1.0.json, server/adaptors/integrations/__data__/repository/amazon_cloudfront/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/amazon_elb/amazon_elb-1.0.0.json, server/adaptors/integrations/__data__/repository/amazon_s3/amazon_s3-1.1.0.json, server/adaptors/integrations/__data__/repository/amazon_s3/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.1.0.json, server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc_schema-1.0.0.sql, server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json, server/adaptors/integrations/__data__/repository/apache/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudtrail/aws_cloudtrail-1.1.0.json, server/adaptors/integrations/__data__/repository/aws_waf/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.1.0.json, server/adaptors/integrations/__data__/repository/haproxy/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/haproxy/haproxy-1.1.0.json, server/adaptors/integrations/__data__/repository/nginx/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
=> [Backport 2.x] Integration enhancements

opensearch_dashboards.json, package.json
Update 2.x to 2.15.0
https://github.com/opensearch-project/opensearch-build/issues/4681
=> Update 2.x to 2.15.0

public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap, public/components/trace_analytics/components/common/plots/service_map_scale.tsx, public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap, public/components/trace_analytics/components/services/services_table.tsx, public/components/trace_analytics/home.tsx
(cherry picked from commit 3df8e90e690fc411abf1bdc9e27854dc6e2cb79e)
* Update the theming in dark mode for scale of the service map
* Add data test-subj for cypress
* Add mode dependency to attributefilter useEffect
*  update test snapshots
https://github.com/opensearch-project/dashboards-observability/issues/1820
=> Minor bug fixes for trace analytics v2

public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/metrics/sidebar/data_source_picker.tsx, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, server/adaptors/metrics/metrics_analytics_adaptor.ts
* Update Metrics datasource text
* Update DSL query for metrics 
* Update traces-logs index prefix to ss4o
https://github.com/opensearch-project/dashboards-observability/issues/1820
=> Update metrics DSL queries and trace logs index

public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/no_results.tsx, public/components/event_analytics/hooks/use_fetch_events.ts, public/services/data_fetchers/ppl/ppl_data_fetcher.ts
- support loading UI when query is running for query assist is enabled or disabled
- avoid recreating nested components in render cycle
=> Fix loading state UI for event analytics

public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/no_results.tsx, public/components/event_analytics/hooks/use_fetch_events.ts, public/services/data_fetchers/ppl/ppl_data_fetcher.ts
=> [2.x] Fix loading state UI for event analytics (#1902)

public/components/application_analytics/__tests__/__snapshots__/log_config.test.tsx.snap, public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap, public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap, public/components/common/search/query_area.tsx, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/panel_modules/panel_grid/__tests__/__snapshots__/panel_grid.test.tsx.snap, public/components/event_analytics/explorer/no_results.tsx, public/components/event_analytics/explorer/query_assist/input.tsx, public/components/metrics/view/__tests__/__snapshots__/metrics_grid.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap
- Change the "PPL Query" label to "Query Assist"
- focus Query Assist form field on load
- update get started text
- update place holder text
- update icon size
=> fix minor issues in query assist UI

public/components/application_analytics/home.tsx
Adding attributefilter field to app analytics
Without this change in App analytics crashes on UI once it is created 
=> Adding attributefilter field to app analytics

public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap, public/components/notebooks/components/notebook.tsx, public/components/notebooks/components/paragraph_components/paragraphs.tsx
UX change for migrate notebook
=> UX copy changes for Notebooks with MDS

public/components/integrations/components/added_integration_overview_page.tsx, public/components/integrations/components/added_integration_table.tsx, public/components/integrations/components/integration_types.ts, public/components/integrations/components/setup_integration_inputs.tsx, public/components/integrations/home.tsx, release-notes/dashboards-observability.release-notes-2.16.0.0.md
MDS support as part of NEO. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5870
=> [Feature] Multi-data Source Support for Integrations

package.json, public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, release-notes/dashboards-observability.release-notes-2.16.0.0.md, yarn.lock
Fix CVEs for ag-grid, ws and braces packages
https://github.com/advisories/GHSA-328p-362g-r48j
https://github.com/advisories/GHSA-3h5v-q93c-6h6q
https://github.com/advisories/GHSA-328p-362g-r48j
=> Backport 2.16 Fix CVEs for ag-grid, ws and braces packages

public/components/datasources/components/manage/integrations/installed_integrations_table.tsx, public/components/integrations/components/added_integration_overview_page.tsx, public/components/integrations/components/added_integration_table.tsx, public/components/integrations/components/integration_types.ts, public/components/integrations/components/setup_integration.tsx, public/components/integrations/components/setup_integration_inputs.tsx, public/components/integrations/home.tsx, release-notes/dashboards-observability.release-notes-2.16.0.0.md
https://github.com/opensearch-project/dashboards-observability/pull/1993
https://github.com/opensearch-project/dashboards-observability/pull/1992
=> [Backport 2.x] backport of integrations for MDS support

release-notes/dashboards-observability.release-notes-2.16.0.0.md
Updated release notes as we have removed Integrations-mds from 2.16
=> updated release notes for 2.16

opensearch_dashboards.json, public/components/application_analytics/components/application.tsx, public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/home.tsx
https://github.com/opensearch-project/dashboards-observability/issues/1878 - trace analytics
App analytics page crash for missing MDS-id https://github.com/opensearch-project/dashboards-observability/issues/1931
=> [Bug] Trace Analytics bug fix for local cluster being rendered

public/components/application_analytics/components/application.tsx, public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/home.tsx
backport for https://github.com/opensearch-project/dashboards-observability/pull/2006
* traces and app analytics fix
* reverted json file
* updated snapshots
---------
https://github.com/opensearch-project/dashboards-observability/issues/1878 
https://github.com/opensearch-project/dashboards-observability/issues/1931
=> [Backport 2.16] Trace Analytics bug fix for local cluster being rendered (#2006)

public/components/application_analytics/components/application.tsx, public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/home.tsx
Backport for https://github.com/opensearch-project/dashboards-observability/pull/2006
* traces and app analytics fix
* reverted json file
* updated snapshots
https://github.com/opensearch-project/dashboards-observability/issues/1878 
https://github.com/opensearch-project/dashboards-observability/issues/1931
=> [Backport 2.x] Trace Analytics bug fix for local cluster being rendered (#2006)

server/routes/getting_started/getting_started_router.ts
`/api/observability/gettingStarted/createAssets` now does not support workspace because it is using static ids for the objects that will be created. This PR is to fix the issue by detecting if there is workspaceId in the request, if so, prepend the workspace id to the objects id and their references.
=> feat: make createAssets API compatible with workspace

release-notes/opensearch-observability.release-notes-2.17.0.0.md
Add release note for 2.17.0
* Relate https://github.com/opensearch-project/dashboards-observability/issues/2042
=> [Release] Add release note for 2.17.0

server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/create_table_vpc_schema-1.0.0.sql
Fix the VPC integration's MV creation query
* Relate https://github.com/opensearch-project/opensearch-catalog/issues/195
=> [Bug Fix] Fix the VPC integration's MV creation query

common/constants/shared.ts, public/components/overview/home.tsx
1. typography for getting started card 
2. overview page title change based on nav group
=> [Fit&Finish] Observability overview page

server/adaptors/metrics/metrics_analytics_adaptor.ts
=> [Bug] [MDS] call to remote cluster has missing else condition

public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
Disable and hide expand button for metrics panel cc. @vamsi-amazon 
=> [BUG] Metrics fixes

.cypress/integration/app_analytics_test/app_analytics.spec.js, public/components/application_analytics/components/app_table.tsx, public/components/application_analytics/components/application.tsx, public/components/application_analytics/home.tsx, public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
* update cypress testing for app analytics
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* replace wait
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* change action menu for metrics
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* update snapshots
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* wait for service entities and trace groups to load
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* load deleted applications
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* remove deleted applications from table without reload
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* fix deleting saved visualizations
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* type in applications to delete
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
---------
Signed-off-by: Ritvi Bhatt …
=> [Manual Backport 2.x] [Cypress Updates] App analytics updates (#2261)

.github/workflows/dashboards-observability-test-and-build-workflow.yml, .github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml, .github/workflows/link-checker.yml, .github/workflows/lint.yml, .github/workflows/verify-binary-install.yml
Minor CI updates and workflow fixes 
Derived from https://github.com/opensearch-project/dashboards-observability/pull/2386
=> Minor CI updates and workflow fixes 

package.json, yarn.lock
=> [CVE] Issue/CVE fix CVE 2024 53382

docs/integrations/setup.md
[Doc] Update the integraiton SOP's publish section
=> [Doc] Update the integraiton SOP's publish section

release-notes/opensearch-observability.release-notes-2.19.2.0.md
=> release notes for 2.19.2

release-notes/opensearch-observability.release-notes-3.0.0.0.md
Release Notes for 3.0.0
https://github.com/opensearch-project/opensearch-build/issues/3747#issuecomment-2836369925
=> Release Notes 3.0.0
