opensearch-project/dashboards-observability

public/components/visualizations/charts/logs_view/logs_view.scss
closes https://github.com/opensearch-project/dashboards-observability/issues/165
The style was added by commit db674583bf026df783dad2553699ea432259354c. I checked doesn't seem to break other places but not sure why it was added
#165 
=> Fix event analytics field blank margin

public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx, public/components/metrics/view/__tests__/metrics_grid.test.tsx
* Fixed PPL errors displayed in viz. container
* Added tool tip preview date picker
#161 
#162 
#163 
#169 
=> Fixed PPL Error in containers & added tool tip to date picker

release-notes/opensearch-observability.release-notes-2.5.0.0.md
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
Release notes for 2.5.0 
=> Add release notes for 2.5

server/routes/notebooks/vizRouter.ts
under notebooks the metric name should be `fetch_visualization` instead of `visualization`.
=> Fix typo in fetch_visualization metrics name

public/components/notebooks/components/notebook.tsx
Reporting plugin has changed the report generation mechanism, and triggering on demand reports from observability plugin no longer works. Remove those broken buttons for now while working on a fix
=> Temporarily hide reporting context menu in notebooks

package.json
Remove antlr post-install step
https://github.com/opensearch-project/observability/issues/1364
=> Remove antlr post-install step

package.json, yarn.lock
Manual backporting CVE fixes for debug dependency.
=> [BACKPORT 2.5] Manual backporting CVE fix

.cypress/integration/1_event_analytics.spec.js, .cypress/utils/event_analytics/constants.js, common/types/explorer.ts, public/components/common/search/search.tsx, public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/save_panel/__tests__/__snapshots__/save_panel.test.tsx.snap, public/components/event_analytics/explorer/save_panel/save_panel.tsx, public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx, public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx, public/components/event_analytics/explorer/visualizations/index.tsx, public/components/event_analytics/hooks/use_render_visualizations.ts
- Update event analytics cypress
- Fix linting errors
=> Cypress test update and related linting fixes

common/types/custom_panels.ts, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.scss, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.scss, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx
* update error handling in viz container
* fixed comments & minor changes
---------
(cherry picked from commit cc9dafe3ee8546b34bea91d17feaaf8a9ffb3b88)
Update error handling in viz container
#161
=> [Backport] Update error handling in viz container (#247)

yarn.lock
(cherry picked from commit 864f28540d062120598a05db5ba1f1ca5c5d57aa)
Manually backport #221 to 2.x
=> [BACKPORT 2.x] fix for debug cve issue (#221)

yarn.lock
(cherry picked from commit 864f28540d062120598a05db5ba1f1ca5c5d57aa)
Manually backport #221 to 2.5.
=> [BACKPORT 2.5] fix for debug cve issue (#221)

public/components/visualizations/visualization.tsx
Remove timeseries data validation to bring back line chart support. 
@anirudha @ps48 will need to discuss how to support both timeseries and line in Observability. 
=> Remove timeseries data validation to get back line chart support

.cypress/integration/4_trace_analytics_dashboard.spec.js, .cypress/integration/5_trace_analytics_services.spec.js, .cypress/integration/6_trace_analytics_traces.spec.js, .cypress/utils/constants.js, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap, public/components/trace_analytics/components/common/filters/filters.tsx, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/mode_picker.test.tsx.snap, public/components/trace_analytics/components/dashboard/mode_picker.tsx, public/components/trace_analytics/components/dashboard/top_groups_page.tsx, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap, public/components/trace_analytics/components/services/services_table.tsx, public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap, public/components/trace_analytics/components/traces/service_breakdown_panel.tsx, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, public/components/trace_analytics/components/traces/span_detail_panel.tsx, public/components/trace_analytics/components/traces/span_detail_table.tsx, public/components/trace_analytics/components/traces/traces_table.tsx, public/components/trace_analytics/home.tsx
Signed-off-by: Derek Ho <dxho@amazon.com>
=> fix up cypress and add jaeger tests

.gitignore, public/components/notebooks/components/helpers/__tests__/reporting_context_menu_helper.test.tsx, public/components/notebooks/components/helpers/reporting_context_menu_helper.tsx, public/components/notebooks/components/notebook.tsx
Add reporting on-demand menu items back in notebooks. Clicking on them will open a new tab of notebooks in `output only` mode and trigger report generation
=> Add reporting on-demand menu items back in notebooks

.cypress/integration/4_trace_analytics_dashboard.spec.js, .cypress/integration/5_trace_analytics_services.spec.js, .cypress/integration/6_trace_analytics_traces.spec.js, .cypress/utils/constants.js, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filters.test.tsx.snap, public/components/trace_analytics/components/common/filters/filters.tsx, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/mode_picker.test.tsx.snap, public/components/trace_analytics/components/dashboard/mode_picker.tsx, public/components/trace_analytics/components/dashboard/top_groups_page.tsx, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap, public/components/trace_analytics/components/services/services_table.tsx, public/components/trace_analytics/components/traces/__tests__/__snapshots__/service_breakdown_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_panel.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap, public/components/trace_analytics/components/traces/service_breakdown_panel.tsx, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, public/components/trace_analytics/components/traces/span_detail_panel.tsx, public/components/trace_analytics/components/traces/span_detail_table.tsx, public/components/trace_analytics/components/traces/traces_table.tsx, public/components/trace_analytics/home.tsx
fix up cypress and add jaeger tests (#265)
* fix up cypress and add jaeger tests
* fix snapshot tests
* fix services cypress file and add jaeger tests
* fix trace cypress and jaeger for traces
---------
(cherry picked from commit 7daf880d7d7dc8b37befc38356e4a21cdb65fe84)
=> [BACKPORT 2.5] cypress test fixes for jaeger 

public/components/notebooks/components/main.tsx
if creation of notebook fails due to invalid name, the user will be dumped onto the notebook table page, with /create persisted in the url. This will prevent the user from being able to get create notebook modal open again unless they refresh the page or manually clear out the url
=> fix bug for failed notebook create

public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx
Add missing change and removal for visualization config panel that is supposed to be in backport PR.
Seems like changes are being automatically merged without showing conflicts
[Correct change in 2.5](https://github.com/opensearch-project/dashboards-observability/commit/add3309b49bff8cb59f160ced924155b7deba2cc#diff-b0426b1ab37d47622085dbe0b1f21c60facbd74790235de037572c0b1af1846dL288)
[Backport PR missing changes for 2.x](https://github.com/opensearch-project/dashboards-observability/pull/291/files#diff-b0426b1ab37d47622085dbe0b1f21c60facbd74790235de037572c0b1af1846d)
For more information on following Developer Certificate of Origin and …
=> Add missing changes for visualization config panel

.github/workflows/dashboards-observability-test-and-build-workflow.yml
The GitHub workflow uses the `engines` from OSD incorrectly. This change fixes that.
=> Fix Node.js and Yarn installation in CI

package.json, release-notes/opensearch-observability.release-notes-2.6.0.0.md
performance-now package was moved from `dev-dependencies` to `dependencies`
* move performance now to run time dep 
=> move performance now to run time dep

public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/event_analytics/explorer/sidebar/__tests__/sidebar.test.tsx, public/components/event_analytics/explorer/sidebar/sidebar.tsx, public/components/event_analytics/explorer/visualizations/index.tsx, public/components/event_analytics/hooks/use_fetch_events.ts
Sidebar related refactoring
- move fields toggling functions to under sidebar component rather than under explorer.tsx
- fix a bug -> when switching to a different index, previous selected fields still shows up under selected fields
- currently any new refresh button click to trigger a search would clear out the selected fields if there are any, as it does not yet have the capability to detect index change for updating fields accordingly. To add such index difference detection would add to data fetching flow which is under refactoring. We may need to add support to update all fields only when index changes
- update tests/snapshots
For …
=> [Refactoring] Explorer sidebar refactoring

.cypress/integration/3_panels.spec.ts
PR #361 is a large fix to Panels Duplication and the associated E2E test.
In order to simplify the review of the E2E test ,this reorganization of 3_panels_spec.ts, including new `describe()` sections, results in a large formatting-only PR and will simplify the subsequent change.
#361 will be temporarily based upon this branch for continued review until this PR is merged.
=> Reorganize 3_panels.spec.ts E2E

public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/helpers/add_visualization_helper.ts, public/components/custom_panels/home.tsx, public/components/custom_panels/redux/panel_slice.ts, public/components/event_analytics/explorer/save_panel/save_panel.tsx, public/services/saved_objects/saved_object_savers/ppl/save_as_current_vis.ts, public/services/saved_objects/saved_object_savers/ppl/save_as_new_vis.ts
Delete fixed (minus toast for delete and rename), separate out bulk update for event analytics add viz to operational panel flow. Still need to do bulk update for SO to add new and old viz
=> bulk update separation

public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx, public/components/custom_panels/redux/panel_slice.ts
Implements replace in new SO panels
=> fix replace in new so panel

public/components/metrics/index.tsx, public/components/notebooks/components/paragraph_components/para_input.tsx
Links re-dircting to explorer page
Fix re-direct links for visualizations in notebooks, metrics
=> Fix re-direct links for visualizations in notebooks, metrics

public/components/notebooks/components/helpers/__tests__/legacy_route_helpers.test.ts, public/components/notebooks/components/helpers/legacy_route_helpers.ts, public/components/notebooks/components/helpers/reporting_context_menu_helper.tsx
Use new URL for redirecting for notebook reports
=> Support new notebooks URL for reporting

public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/custom_panel_view_so.tsx, public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/home.tsx, public/components/custom_panels/redux/panel_slice.ts
Panel View SavedObject
- Duplicate Action
- protect render from invalid record
- hide render while loading
=> Recover Panel View Legacy - Duplicate Action

public/components/event_analytics/explorer/events_views/doc_flyout.tsx, public/components/event_analytics/explorer/events_views/surrounding_flyout.tsx
Fix doc viewer flyout styling in explorer
Surrounding & Doc flyout use now class `obsExplorer` as parent div.
=> Fix doc viewer flyout styling in explorer

public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/custom_panel_view_so.tsx, public/components/custom_panels/helpers/modal_containers.tsx, public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/home.tsx, public/components/custom_panels/panel_modules/empty_panel.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx, public/components/custom_panels/redux/panel_slice.ts, public/components/event_analytics/explorer/events_views/doc_flyout.tsx, public/components/event_analytics/explorer/events_views/surrounding_flyout.tsx, public/components/metrics/top_menu/top_menu.tsx, public/plugin.ts, public/services/saved_objects/saved_object_savers/ppl/save_as_new_vis.ts
Rename all references to Observability Dashboard
Includes OSD-core Dashboard registration of Observabiltiy Dashboards to Dashboards / Dashboards List
=> Rename Panels => Observability Dashboard

.cypress/integration/2_notebooks.spec.js, public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap, public/components/notebooks/components/main.tsx, public/components/notebooks/components/note_table.tsx, public/components/notebooks/components/notebook.tsx
Fix notebooks issue with cypress and minor bugs from left nav
=> notebooks fix for cypress and minor bugs

.cypress/integration/4_trace_analytics_dashboard.spec.js, .cypress/integration/5_trace_analytics_services.spec.js, .cypress/integration/6_trace_analytics_traces.spec.js
=> Update traces integration tests

public/components/custom_panels/custom_panel_view_so.tsx, public/components/custom_panels/home.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx
Fix panel visualization preview, new viz workflow
Fixes below issues:
1. Panels add visualization flyout, doesn't contain any new visualizations created
2. Preview visualizations before add, don't work with new visualizations
=> Fix panel visualization preview & new viz workflow

.cypress/integration/3_panels.spec.ts, public/components/custom_panels/custom_panel_view_so.tsx, public/components/trace_analytics/requests/dashboard_request_handler.ts, public/plugin.ts, public/services/saved_objects/saved_object_savers/ppl/save_as_new_query.ts
Update to include BASE_URL if basePath is defined. Since create url is just a direct nav and needs the basePath when passing props to the provider, the source code no longer appends the basePath to keep these URLs consistent.
A feature should consolidate the basePaths in the dashboard listing service so that createUrl also adds the base path. At which point we no longer need the base path.
Also removed some rogue console logs and setToast.
Core PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3922
n/a …
=> [Dashboard listing] update edit url and view url

.cypress/integration/3_panels.spec.ts, public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/custom_panel_view_so.tsx, public/components/custom_panels/redux/panel_slice.ts
- added check if dashboard with same name already exists
=> Add Error handling on duplicate dashboard names

public/components/event_analytics/explorer/explorer.tsx, public/services/data_fetchers/ppl/ppl_data_fetcher.ts
Bug that being fix - Overriding a timestamp doesn't work in event analytics sidebar.
=> Fix timestamp overriding issue

public/services/saved_objects/saved_object_client/saved_objects_actions.ts
Need to add unit tests. When no osd items, the map key does not exist, and .concat() will fail
=> Fix delete failure when no osd item selected

.cypress/integration/3_panels.spec.ts, common/constants/custom_panels.ts, common/constants/shared.ts, public/components/common/toast/index.tsx, public/components/custom_panels/__tests__/custom_panel_view.test.tsx, public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/custom_panel_view_so.tsx, public/components/custom_panels/home.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx, public/components/custom_panels/redux/panel_slice.ts, public/framework/core_refs.ts, public/plugin.ts, test/setup.jest.ts
(cherry picked from commit a9d1d37035f41d5e81f521f16dd4ebcfaf478398)
[BACKPORT MAIN]Add Toasts to Observability Dashboards (#435)
=> [BACKPORT MAIN]Add Toasts to Observability Dashboards  (#435)

public/components/event_analytics/explorer/explorer.scss, public/components/metrics/index.scss
Issue: 
in advanced setting page of Core Dashboard, if you made a change, a banner should show up on the bottom of the page
but currently in main, it is missing.
**Root cause**:
Changes in main of dashboard core moved that banner code from a sibling div to under the main body with an id of '#opensearch-dashboards-body'. Observability also refer to this id for its own styling previously affecting that banner.
Versions like 2.7 which do not see such bug have DOM structure like
<br><br>
where banner section with 'label Page level controls' locates out side of 'opensearch-dashboards-body' whereas in main:
<br><br>
<br><br>
It got moved to under body div. <br><br>
**Fix** 
Removed styling which didn't have actual effect currently for observability but affecting that banner. Also moving …
=> Remove styling causing issue for banner in advanced settings

public/components/notebooks/components/helpers/__tests__/reporting_context_menu_helper.test.tsx, public/components/notebooks/components/helpers/reporting_context_menu_helper.tsx, public/components/notebooks/components/notebook.tsx
(cherry picked from commit 0527730d9c7a7743e03061048937c6b3aa611788)
Add reporting on-demand menu items back in notebooks. Clicking on them will open a new tab of notebooks in output only mode and trigger report generation
=> [Backport 2.x] Add reporting on-demand menu items back in notebooks (#229)

.cypress/integration/4_trace_analytics_dashboard.spec.js, .cypress/integration/5_trace_analytics_services.spec.js, .cypress/integration/6_trace_analytics_traces.spec.js, .cypress/utils/constants.js
Fixes for cypress testing for Trace Analytics Services & Traces
Added assertion checks to allow page to load in place of waits.
=> Cypress Testing v12.8.1 - Trace Analytics (Services & Traces) fixes

common/utils/index.ts, common/utils/query_utils.ts, public/components/event_analytics/explorer/explorer.tsx, public/services/data_fetchers/ppl/ppl_data_fetcher.ts
BugFix Application Analytics timestamp query error.
=> BugFix Application Analytics timestamp query error

common/constants/shared.ts, package.json, server/adaptors/integrations/integrations_adaptor.ts, server/adaptors/integrations/types.ts, server/routes/index.ts, server/routes/integrations/__tests__/integrations_router.test.ts, server/routes/integrations/integrations_router.ts, yarn.lock
As part of breaking the integrations project into smaller pieces, the first step is to stub the router. On one side, the adaptor implementation will be filled in behind it, while on the other, the front-end can be split up and shared in front of it.
As-is, the router should catch errors and return 500s for every request. Nothing should crash the server.
=> Stub router for integrations project

server/adaptors/integrations/repository/__test__/integration.test.ts, server/adaptors/integrations/repository/__test__/repository.test.ts, server/adaptors/integrations/repository/integration.ts, server/adaptors/integrations/repository/repository.ts, server/adaptors/integrations/types.ts, server/adaptors/integrations/validators.ts, server/adaptors/opensearch_observability_plugin.ts
Followup from #547 and part of breaking down #476, this PR pulls in the repository class, as well as some recent type system updates. The bulk of the logic is in `integration.ts`, with a light wrapper from `repository.ts`. Merging in the actual integrations content will be a separate PR, so for now this code will always return empty lists or null respectively when asked to list or retrieve integrations.
The next step will be implementing the integrations backend, which connects the Repository class to the integrations router. …
=> Merge in repository classes from osints/dev

server/adaptors/integrations/__test__/builder.test.ts, server/adaptors/integrations/__test__/kibana_backend.test.ts, server/adaptors/integrations/integrations_builder.ts, server/adaptors/integrations/integrations_kibana_backend.ts, server/adaptors/integrations/types.ts, server/adaptors/integrations/validators.ts, server/plugin.ts, server/routes/integrations/__tests__/integrations_router.test.ts, server/routes/integrations/integrations_router.ts
Successor PR to #552, this PR implements the backend connecting the routes, repository, and .kibana saved objects. After this PR and #559 are merged, the integrations backend should be fully functional, and the frontend can be merged in further PRs.
=> Merge Kibana backend from osints/dev into main

package.json, server/routes/integrations/integrations_router.ts, yarn.lock
Sanitization of filenames passed to the static endpoint was added in osints/dev but not merged into main. This PR copies that sanitization logic over.
Note: Not a security vulnerability unless #565 gets merged first.
=> Copy path sanitization from osints/dev

public/components/metrics/index.tsx
Replace Metrics panel-separator (vertical) with ResizeableContainer slider.
https://github.com/opensearch-project/dashboards-observability/assets/11318/a99eb85c-e371-4853-b85b-08f596c0fb54
=> Replace metrics panel-separator with ResizableContainer

package.json, yarn.lock
Upgrade tough-cookie and semver
* Upgrade tough-cookie to fix CVE-2023-26136
* Add semver resolution to patch CVE-2022-25883
=> Upgrade tough-cookie and semver (#619)

package.json, yarn.lock
Upgrade tough-cookie and semver
* Upgrade tough-cookie to fix CVE-2023-26136
* Add semver resolution to patch CVE-2022-25883
=> [Backport 2.x] Adding cookie cve fix

server/common/metrics/constants.ts
https://github.com/opensearch-project/dashboards-observability/pull/638
metrics constant file was broken due to this PR, there was this typescript error that was ignored. we should make CI fail on typescript errors
```
Diagnostics:
Property 'forEach' does not exist on type '"application_analytics" | "operational_panels" | "event_analytics" | "notebooks" | "trace_analytics" | "metrics_analytics" | "integrations"'.
Property 'forEach' does not exist on type '"application_analytics"'. [2339]
```
This PR fixes the metrics constant file by restoring the previous version, probably broken due to merge conflict
For more information on following …
=> revert integrations change metrics

.cypress/plugins/index.js
Adds back cypress watch and reload, yarn cypress:open does not work without it
=> Adds cypress watch and reload plugin

.cypress/integration/9_integrations.spec.js, public/components/integrations/components/add_integration_flyout.tsx
Fix Bug where integration cannot be created from UI if the name of the integration instance is changed prior to validating data source mappings.
Fix: #712 
=> fix name change bug and modify test to test behavior

.cypress/integration/9_integrations.spec.js, public/components/integrations/components/add_integration_flyout.tsx, public/components/integrations/components/added_integration_table.tsx, public/components/integrations/components/integration_assets_panel.tsx
Hooks up the search bar properly for added and integration assets
Fix #715 
=> Search bar fixes

server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.1.json, server/adaptors/integrations/__test__/local_repository.test.ts
Link field was added to the integration which causes validation errors.
Resolves #760 
=> Remove link field from Nginx

common/constants/integrations.ts, public/components/integrations/components/added_integration_table.tsx, public/components/integrations/components/available_integration_overview_page.tsx
Removes instance of hardcoded integration categories list. Also removes an unrelated hardcoded template list that results in a very similar bug in the added integration list.
Resolves #780 
=> Make integration category and template lists dynamic

server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json, server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json, server/adaptors/integrations/__test__/local_repository.test.ts
The type for the VPC Flow log was corrupted in #740, leading to the VPC integration displaying lots of errors. This is a different failure mode from the usual result when the type is messed up, so it went undetected for a while.
This PR:
- Fixes the problem
- Adds a test to prevent recurrence
Resolves #792 
=> Re-apply fix for VPC type

public/components/integrations/components/added_integration_table.tsx
Fixes an invisible merge conflict: one PR deleted a variable while another PR added an instance of using it. Result is that whole integrations plugin doesn't render.
=> Remove dependence on integrations variable

public/components/integrations/components/integration.tsx
When updating an index template with the same name, OpenSearch rejects the request if it invalidates any old indices. This affects the integration plugin's sample data creation, since it was previously only using type information for creating indices, and this led to collisions with index patterns. This PR also adds name information to the created indices, in order to avoid these collisions.
Resolves #812 
=> Fix index name collisions on integration sample creation.

server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json, server/adaptors/integrations/__data__/repository/apache/schemas/logs-apache-1.0.0.mapping.json
Changes log mapping names to be apache-specific, to avoid conflict with other log index patterns.
#812 
[Backport comments](https://github.com/opensearch-project/dashboards-observability/pull/800#discussion_r1283513166)
=> Changed log mappings to be apache-specific

server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json, server/adaptors/integrations/__data__/repository/aws_elb/schemas/logs-elb-1.0.0.mapping.json
Changes log mapping file names to avoid conflict with other log index patterns
#812 
[Backport comments](https://github.com/opensearch-project/dashboards-observability/pull/801#discussion_r1283506729)
=> Changed logs mappings to be logs-elb

server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
Signed-off-by: Daniel Dong <danieldong51@amazon.com>
Co-authored-by: Daniel Dong <danieldong51@amazon.com>
(cherry picked from commit a4b764ace27ba2c5141623b67fa3ac09cc2d3ff7)
Backports URL changes to Apache to 2.9
https://github.com/opensearch-project/dashboards-observability/pull/811
=> [BACKPORT 2.9] Apache URL fix (#811)

.github/workflows/backport.yml, public/components/metrics/sidebar/__tests__/__snapshots__/searchbar.test.tsx.snap, public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
The current CI is failing on main for 3 reasons:
- Snapshots for sidebar tests are outdated
- E2E workflow is broken overall
- Backport workflow triggering early if a PR is labeled before merged
This PR updates the snapshots and adds a check so backport only runs when a PR is merged. E2E was disabled separately, it can be re-enabled when someone has the time to fix it.
N/A
=> Fix failing CI

.github/workflows/dashboards-observability-test-and-build-workflow.yml
I did some poking around on why our tests might be so slow in CI, and discovered that by default Jest limits itself to 50% of CPU resources. GH Actions has 2 cores, so setting it manually may make our tests run considerably faster.
This is mostly just experimental to see what the difference is.
N/A
=> Speed up unit testing CI by updating maxWorkers setting

server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json, server/adaptors/integrations/__data__/repository/apache/schemas/logs_apache-1.0.0.mapping.json
Due to mixed revision and backport events, Apache has two broken PRs open and 2.x + 2.9 are both out of date. This is one of two syncing PRs to close #800 and #833.
=> Copy latest Apache version to 2.9

public/components/integrations/components/integration_overview_panel.tsx
Per UX team feedback, this PR switches the order of the "Try it" button and switches its shade to make the two buttons stand out as separate options.
N/A
=> Switch Integrations "try it" button to be secondary

.github/workflows/dashboards-observability-test-and-build-workflow.yml, public/components/integrations/components/add_integration_flyout.tsx
As the Bootstrap command in CI is inconsistent, this has been causing a lot of delays in getting CI feedback in PRs. This PR seeks to address this with a few safeguards:
1. Advice from the [OSD Developer Guide](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md) was applied to update the network timeout. In their own CI they use this network setting and also have a backup call in case it fails. They also use a `clean` which may address some inconsistency, though it should be a no-op in a CI setting.
2. `fail-fast` is disabled in the CI, so even if the measures from (1) are unsuccessful, we will at least receive some feedback from the other two runs without needing a full re-run.
3. The results are cached to both reduce the effects of the issue and …
=> Make OSD Bootstrap more sturdy in CI

README.md
Update the readme.md file to present screenshots from the dashboard
Integration screenshots should be moved down to the screenshots section
=> update the README.md with Screenshots section

server/adaptors/integrations/__test__/local_repository.test.ts, server/adaptors/integrations/__test__/validators.test.ts, server/adaptors/integrations/repository/__test__/integration.test.ts, server/adaptors/integrations/repository/integration.ts, server/adaptors/integrations/validators.ts
While working on the unrelated [remote catalog](https://github.com/opensearch-project/opensearch-catalog/issues/69) feature, I separately refactored our Ajv usage to provide better error messages and help break tight coupling. This change on its own is small and generally applicable, so I've moved it to its own PR.
N/A
=> Refactor integration validation logic with a cleaner interface

common/constants/notebooks.ts, package.json, server/adaptors/custom_panels/custom_panel_adaptor.ts, server/adaptors/notebooks/default_backend.ts, server/adaptors/notebooks/index.ts, server/adaptors/ppl_datasource.ts, server/common/helpers/notebooks/default_notebook_schema.ts, server/common/helpers/notebooks/query_helpers.ts, server/common/helpers/notebooks/sample_notebooks.ts, server/common/helpers/notebooks/wreck_requests.ts, server/common/metrics/metrics_helper.ts, server/common/metrics/types.ts, server/common/types/index.ts, server/routes/application_analytics/app_analytics_router.ts, server/routes/custom_panels/panels_router.ts, server/routes/dsl.ts, server/routes/index.ts, server/routes/metrics/metrics_rounter.ts, server/routes/notebooks/noteRouter.ts, server/routes/notebooks/paraRouter.ts, server/routes/notebooks/sqlRouter.ts, server/routes/ppl.ts, server/services/facets/dsl_facet.ts, server/services/facets/ppl_facet.ts, server/services/queryService.ts, yarn.lock
As part of the long-term goal of #676, this is a small maintenance PR that fixes all linting errors for the `server` directory. In addition to autofixable lints that form the majority of the errors (the first commit), this PR addresses 16 manual-fix problems (the rest of them). I also found one unused dev dependency that I removed.
After this PR, there are 999 `yarn lint` errors remaining in other directories, which reduces to 166 when running `yarn lint --fix`. Saving from running a full `--fix` to reduce the surface for merge conflicts.
<details>
<summary>16 manually fixed problems</summary>
<pre><code>yarn run v1.22.19
$ yarn lint:es server
$ node ../../scripts/eslint server
/Users/sawiddis/Documents/code/dashboards/plugins/dashboards-observability/server/adaptors/custom_panels/custom_p …
=> Fix all yarn lints for server directory

common/utils/index.ts, public/components/application_analytics/helpers/utils.tsx, public/components/common/query_utils.ts, public/components/event_analytics/explorer/sidebar/field_insights.tsx, public/components/event_analytics/hooks/use_fetch_patterns.ts
Move query_utils module to /public.
This module contains only functions used in browser front-end code.  Having this module in /common causes a server restart on every change.  The query_utils module will be updated extensively in Metrics Edit feature.
=> Move query_utils to /public

.cypress/integration/2_notebooks.spec.js, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/para_output.test.tsx, public/components/notebooks/components/paragraph_components/para_output.tsx, public/components/notebooks/components/paragraph_components/paragraphs.tsx, public/components/notebooks/index.scss
Update Notebook Paragraph CSS to ensure wrap-break on all text - even verylongrunonwords.
#769
- [-] New functionality has been documented.
- [-] New functionality has javadoc added
- [-] New functionality has user manual doc added
=> Add wrap break-all to Noteobook CodeBlock output

common/constants/data_connections.ts, opensearch_dashboards.json, public/components/data_connections/components/__tests__/__snapshots__/manage_datasource_description.test.tsx.snap, public/components/data_connections/components/acceleration_ui/acceleration_header.tsx, public/components/data_connections/components/acceleration_ui/acceleration_home.tsx, public/components/data_connections/components/acceleration_ui/acceleration_indices.tsx, public/components/data_connections/components/acceleration_ui/management/acceleration_management.tsx, public/components/data_connections/components/acceleration_ui/management/management_table.tsx, public/components/data_connections/components/acceleration_ui/management/source_selector.tsx, public/components/data_connections/components/datasource.tsx, public/components/data_connections/components/manage_datasource_description.tsx, public/components/data_connections/components/manage_datasource_table.tsx, public/components/data_connections/home.tsx, public/framework/core_refs.ts, public/plugin.ts
Add acceleration management UI skeleton
* Acc. Home Page 
* Selector for Data source
* Acceleration management Table 
=> Add acceleration management UI 

public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/field.test.tsx.snap, public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/event_analytics/explorer/sidebar/field.tsx, public/components/event_analytics/explorer/sidebar/sidebar.scss, public/components/event_analytics/explorer/sidebar/sidebar.tsx
Changed all the classnames for the sidebar component to avoid conflicts
=> refactored classnames for sidebar

.github/workflows/integration-tests-workflow.yml
Per side-channel discussion, we're looking at re-enabling E2E tests to run nightly (as opposed to on every PR).
Part of improving our testing strategy in response to #1001.
N/A
=> Add nightly cron schedule to E2E workflow

common/constants/shared.ts, public/components/custom_panels/helpers/__tests__/__snapshots__/utils.test.tsx.snap, public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/visualizations/config_panel/__tests__/__snapshots__/config_panel.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/bar.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/gauge.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/heatmap.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/histogram.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/horizontal_bar.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/line.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/metrics.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/pie.test.tsx.snap, public/components/visualizations/charts/__tests__/__snapshots__/treemap.test.tsx.snap, public/components/visualizations/plotly/__tests__/__snapshots__/plotly.test.tsx.snap
In explorer, modifies the color of the chart and changes the higher level look of explorer from a single page to multiple floating islands
=> adjust explorer chart color and spacing

public/components/common/query_utils/index.ts
Recently added query_utils/index.ts is missing an import for moment.
=> Fix missing import 'moment' on query_utils.

public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx
Modify Metric Explorer to display single-line graphs only, no legends
=> Metrics Explorer - single-line graph only, no legends

common/constants/data_connections.ts, common/types/data_connections.ts, public/components/datasources/components/__tests__/__snapshots__/manage_data_connections_table.test.tsx.snap, public/components/datasources/components/new/configure_datasource.tsx, public/components/datasources/components/new/configure_prometheus_datasource.tsx, public/components/datasources/components/new/configure_s3_datasource.tsx, public/components/datasources/components/new/name_row.tsx, public/components/datasources/components/new/query_permissions.tsx, public/components/event_analytics/explorer/events_views/data_grid.tsx, public/components/event_analytics/explorer/events_views/docViewRow.tsx, public/components/event_analytics/explorer/events_views/surrounding_flyout.tsx, public/components/event_analytics/utils/utils.tsx, public/components/notebooks/components/helpers/__tests__/sampleZeppelinNotebooks.tsx, public/components/notebooks/components/helpers/__tests__/zeppelin_parser.test.tsx, public/components/notebooks/components/helpers/default_parser.tsx, public/components/notebooks/components/helpers/zeppelin_parser.tsx, public/components/notebooks/components/notebook.tsx, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap, public/components/notebooks/components/paragraph_components/para_output.tsx, public/components/notebooks/components/paragraph_components/paragraphs.tsx, public/components/notebooks/index.scss
- Fixes documentation linking
- Adds form validation to name (empty name, duplicate name)
- Adds form validation to query permissions group
- Reverts Notebooks changes #974 #985 
- Explorer bug fix for surrounding changes
- updated jest tests
=> Reverting notebooks changes, add docs/validation to datasources, explorer minor fixes

common/constants/data_connections.ts, public/components/datasources/components/new/configure_s3_datasource.tsx
=> Add callout and modify content for S3 datasource

public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/setup_integration.tsx
Instead of disabling, remove the choice from the dropdown entirely if it's not present.
=> Fix dropdown display behavior

common/constants/data_connections.ts, public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/manage/data_connection.tsx, public/components/datasources/components/new/configure_s3_datasource.tsx, public/components/datasources/components/new/new_datasource_card_view.tsx
Remove integrations card from datasources
=> Remove integrations card from datasources

public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/setup_integration.tsx
The current integrations setup page has had mismatched headers due to strange behavior of `EuiTitle`. We switch it to `EuiText` and update the header scales to look correctly matched.
Before:
After:
N/A
=> Switch heading types on integrations setup page

public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/event_analytics/explorer/sidebar/sidebar.tsx
Fix countDistribution access error when countDistribution not available.
Explorer Sidebar has React-DND warnings for missing draggableId / droppableId
Explorer workspace has error on countDistribution when it's not available.
=> Quiet react-dnd draggableId/droppableId warnings.

public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/__tests__/setup_integration.test.tsx, public/components/integrations/components/available_integration_overview_page.tsx, public/components/integrations/components/create_integration_helpers.ts, public/components/integrations/components/setup_integration.tsx, server/adaptors/integrations/repository/fs_data_adaptor.ts
Per UX feedback, instead of setting a toast when integration setup fails, we use a callout. This PR also includes minor changes to button styling and fixes a bug with integration category selection.
=> Switch from toast to callout for integration set up failures

public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/setup_integration.tsx
Per 2.11 bug bash: If an integration being set up has no display name or no data source selected, then it still adds an invalid integration. This PR adds the quick patch of disabling the button when the integration is missing required fields.
N/A
=> Disable integration set up button if invalid

public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/field.test.tsx.snap, public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/event_analytics/explorer/sidebar/__tests__/field.test.tsx, public/components/event_analytics/explorer/sidebar/__tests__/sidebar.test.tsx, public/components/event_analytics/explorer/sidebar/field.tsx, public/components/event_analytics/explorer/sidebar/sidebar.tsx
=> disabling inspect and default pattern/timestamp buttons when using async data sources

server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_mv_vpc-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_table_vpc-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/refresh_mv_vpc-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json, server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/assets/refresh_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Following the steps of the ELB integration, this adds S3 queries for the Nginx and VPC integrations.
N/A
=> Add S3 integration for Nginx and VPC

public/components/integrations/components/setup_integration.tsx, server/adaptors/integrations/__data__/repository/aws_elb/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_elb/assets/refresh_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json, server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_mv_vpc-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/refresh_mv_vpc-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json, server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/assets/refresh_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json
Instead of doing the refresh synchronously as part of integration installation, we configure the MV for autorefresh and let it run in the background. This can lead to some start-up time for integrations before showing data, but speeds up the installation process.
N/A
=> Remove manual refresh for S3 integrations

server/adaptors/integrations/__test__/local_repository.test.ts, server/adaptors/integrations/__test__/manager.test.ts, server/adaptors/integrations/integrations_manager.ts, server/adaptors/integrations/repository/__test__/repository.test.ts, server/adaptors/integrations/repository/fs_data_adaptor.ts, server/adaptors/integrations/repository/repository.ts
This PR does some refactoring of the repository class to better handle recursive directories and make its role more flexible. There are still some updates needed to add searching a local recursive repository (mostly regarding locating specific integrations), but that will be enabled when catalog metadata is added.
Resolves #1236 
=> Refactor repository reading for recursive directory searching

public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap, public/components/notebooks/components/paragraph_components/para_output.tsx, public/components/notebooks/components/paragraph_components/para_query_grid.tsx, public/components/notebooks/index.scss
Wrap CodeBlock paragraph output wtih forced truncation of long text
fixes #1237
=> Add wrapAll to paragarph output on CodeBlocks

release-notes/dashboards-observability.release-notes-2.11.1.0.md
=> Relase Notes 2.11.1

public/components/notebooks/index.scss
This PR fixes data grid overlap issue in full screen mode. 
https://github.com/opensearch-project/dashboards-observability/issues/1270
=> Style changes for rendering fullscreen data grid in notebooks

codecov.yml
In my continuing campaign of [being minorly inconvenienced by our codecov badge](https://github.com/opensearch-project/dashboards-observability/pull/1258), I also noticed that because codecov isn't correctly handling the relative directory of the test runner, it's not producing results with line-by-line coverage. This PR is another one-liner fix that activates the feature by adding a [path fix](https://docs.codecov.com/docs/fixing-paths).
N/A
=> Add a codecov directory fix to the config

public/components/event_analytics/explorer/llm/input.tsx
Query Assistant in the Event Explorer offers AI insight when a natural language query is generated an run. This PR removes the insights when the resulting query has no returned data.
=> Remove Summary When Generated PPL Query Returns No Reuslts

.github/workflows/integration-tests-workflow.yml
Reference to the [comment](https://github.com/opensearch-project/dashboards-observability/pull/1299#issuecomment-1856485992) on #1299, this PR includes following minor changes:
- Change the OSD checking step by using streaming instead of looping 
- Add dynamic naming for each parallel job
- Enabled this workflow on PR
- Remove a duplicate group of notebooks_test
* Relate #1299 
=> [Forwardport main] Minor changes for cypress workflow

.eslintignore, .eslintrc.js, .github/workflows/lint.yml
Add linter CI to lint only changed files including
- *.ts, 
- *.tsx
- *.js
The linting will be ran only on changes matching above patterns in that PR.
Sample linting run result
https://github.com/mengweieric/dashboards-observability/actions/runs/7215956806/job/19661217812#step:8:1
Sample annotation when linting errors found
https://github.com/mengweieric/dashboards-observability/commit/305287356b68ccd4a1a14873acf1ccd130a8eb9a#diff-2790e5916efcabbaa1ad67efe53928cc72a31ecdf3094cfd0c9582471f91530eL85 …
=> Add linter CI

public/components/common/query_utils/index.ts, public/components/custom_panels/helpers/utils.tsx, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/para_output.tsx, public/components/notebooks/components/paragraph_components/paragraphs.tsx
Observability Visualizations fail to load on Notebook
=> Fix for Notebook Observability Visualization loading

.eslintignore, .eslintrc.js, .github/workflows/lint.yml, package.json
https://github.com/opensearch-project/dashboards-observability/pull/1301
=> [BACKPORT] Backport linter CI to 2.x

opensearch_dashboards.json, public/dependencies/components/ppl_visualization_model.tsx, public/dependencies/register_assistant.tsx, public/framework/core_refs.ts, public/plugin.ts, public/types.ts, server/parsers/ppl_parser.ts, server/plugin.ts, server/types.ts
Enable ppl_visualization with Chatbot.
=> [Feature] Enable ppl visualization in Chatbot

public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/metrics/redux/slices/metrics_slice.ts, public/components/metrics/sidebar/sidebar.tsx, public/components/metrics/view/metrics_grid.tsx, public/services/requests/ppl.ts
Badkport #1309 "Metric Loading Loop fix" to main
=> [Backport main] Bugfix/metric-loading-loop (#1309)

.eslintrc.js, .github/workflows/lint.yml
succeeded on no matched file: https://github.com/opensearch-project/dashboards-observability/actions/runs/7281188230/job/19841193026#step:8:3
fails on having lint error: https://github.com/mengweieric/dashboards-observability/actions/runs/7281399534/job/19841832379
=> Fix no matching issue corner case for lint CI

public/components/common/query_utils/__tests__/query_utils.test.tsx, public/components/common/query_utils/index.ts, public/components/event_analytics/explorer/events_views/data_grid.scss, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/para_output.test.tsx, public/components/notebooks/components/paragraph_components/para_output.tsx
Also fix an scss error.
Notebook visualizations date pass-through from Notebook Paragraph is corrected.
=> Correct date pass-through on Notebook Visualizations.

public/components/common/query_utils/__tests__/query_utils.test.tsx, public/components/common/query_utils/index.ts, public/components/event_analytics/explorer/events_views/data_grid.scss, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/para_output.test.tsx, public/components/notebooks/components/paragraph_components/para_output.tsx
=> [Backport] Backport/backport 1327 to main

.github/draft-release-notes-config.yml, .github/workflows/enforce-labels.yml
Copies the mandatory PR label action from [observability](https://github.com/opensearch-project/observability/).
Closes #1281.
=> Add enforce-labels action

.eslintrc.js, .github/workflows/lint.yml
* no matching corner case
* adjust some linting rules
* using bash array
* improve linter
* remove redundant check
---------
=> [BACKPORT]Fix no matching issue corner case for lint CI (#1317)

.cypress/integration/integrations_test/integrations.spec.js, .eslintrc.js, public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/setup_integration.tsx
Looks like fixes were lost in backporting, this PR copies them over. This fixes the integration tests action for integrations on the 2.x branch.
N/A
=> Pull integrations integration test fixes to 2.x

server/index.ts, server/routes/query_assist/routes.ts, server/routes/query_assist/utils/__tests__/agents.test.ts, server/routes/query_assist/utils/agents.ts
Follow up pr for #1325 
Search for agent id by name defined in opensearch_dashboards.yml. Sample config
```yml
assistant.chat.enabled: true
observability.query_assist.enabled: true
observability.query_assist.response_summary_agent_name: "Response summary agent"
observability.query_assist.error_summary_agent_name: "Error summary agent"
observability.query_assist.ppl_agent_name: "PPL agent"
```
Search triggers when no cached agent id matching the name, or when cached agent gets deleted and ml-commons returns 404 agent not found. …
=> support searching agent by name

public/components/common/helpers/ppl_docs/commands/dedup.ts, public/components/common/helpers/ppl_docs/commands/eval.ts, public/components/common/helpers/ppl_docs/commands/fields.ts, public/components/common/helpers/ppl_docs/commands/head.ts, public/components/common/helpers/ppl_docs/commands/parse.ts, public/components/common/helpers/ppl_docs/commands/rare.ts, public/components/common/helpers/ppl_docs/commands/rename.ts, public/components/common/helpers/ppl_docs/commands/search.ts, public/components/common/helpers/ppl_docs/commands/sort.ts, public/components/common/helpers/ppl_docs/commands/stats.ts, public/components/common/helpers/ppl_docs/commands/syntax.ts, public/components/common/helpers/ppl_docs/commands/top.ts, public/components/common/helpers/ppl_docs/commands/where.ts, public/components/common/helpers/ppl_docs/functions/condition.ts, public/components/common/helpers/ppl_docs/functions/datetime.ts, public/components/common/helpers/ppl_docs/functions/full_text_search.ts, public/components/common/helpers/ppl_docs/functions/math.ts, public/components/common/helpers/ppl_docs/functions/string.ts, public/components/common/helpers/ppl_docs/language_structure/datatypes.ts, public/components/common/helpers/ppl_docs/language_structure/identifiers.ts, public/components/common/helpers/ppl_docs/overview.tsx
Revises PPL in-produce for clarity and edits grammatical, spelling, and other writing errors. 
UX note: The manual opens to the `where` command section. Update to open to the `Overview` section. See the following image for reference. 
https://github.com/opensearch-project/documentation-website/issues/1152
=> [DOC]Revise and edit PPL in-product documentation

public/components/common/helpers/ppl_docs/commands/syntax.ts, public/dependencies/components/__snapshots__/data_grid_container.test.tsx.snap
Update jest snapshot and fix failing build
CI was broken due to this PR: https://github.com/opensearch-project/dashboards-observability/pull/1233 and upstream change in `OuiDataGridProps` 
=> Update jest snapshot and fix failing build 

.cypress/integration/notebooks_test/notebooks.spec.js, .cypress/utils/constants.js, public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap, public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap, public/components/notebooks/components/__tests__/note_table.test.tsx, public/components/notebooks/components/note_table.tsx, public/components/notebooks/components/notebook.tsx, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_input.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap, public/components/notebooks/components/paragraph_components/para_input.tsx, public/components/notebooks/components/paragraph_components/para_output.tsx, public/components/notebooks/components/paragraph_components/paragraphs.tsx
Update notebooks snapshots and cypress
#1338 
=> Update notebooks snapshots and cypress

public/components/common/search/query_area.tsx, public/components/common/search/search.tsx, public/components/event_analytics/explorer/query_assist/input.tsx
Set timerange to be consistent as showed on UI
=> (query assist) enforce timerange to `QUERY_ASSIST_START_TIME`

.github/workflows/lint.yml
make it fail after linting all files
https://github.com/opensearch-project/dashboards-observability/pull/1369#issuecomment-1904937003
=> improve lint workflow to avoid fast fail

server/parsers/ppl_parser.ts
Before we filter ppls to make sure it includes `stats by` as ppl visualization requires two dimensions to render. However in data grid, one dimension is enough so the filter function is useless.
=> feat: for data grid no need to filter stats by

public/components/event_analytics/explorer/events_views/docViewer.tsx
Fix the trace link from event viewer (gif video included):
=> Fix trace link in event viewer

server/adaptors/integrations/repository/index_data_adaptor.ts
Based on #1389 and PR feedback from @mengweieric, this PR optimizes retrieving integration data over the network. Benchmark statistics included in the linked issue, locally it gives an 80% speedup and will scale much better to larger workloads (in the future we can also consider pagination). It's not as fast as caching everything in-memory, but compared to the relative complexity of caching I think it's a good compromise.
Existing tests pass without modification.
Closes #1389.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-ce …
=> Optimize searches for integration data

public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
PPL filters were unable to be added in Observability Dashboards since [`pplFilterValue`](https://github.com/opensearch-project/dashboards-observability/blob/main/public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx#L293) is not accepted by [`renderSavedVisualization`](https://github.com/opensearch-project/dashboards-observability/blob/main/public/components/custom_panels/helpers/utils.tsx#L190). One-liner to correctly pass in the parameters, as it is done [here](https://github.com/opensearch-project/dashboards-observability/blob/main/public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx#L276).
Video of Cypress test [`Add ppl filter to panel`](https://github.com/opensearch-project/dashboards-observabili …
=> [BUG] Fix Panels PPL Filter

public/components/event_analytics/explorer/query_assist/__tests__/hooks.test.ts, public/components/event_analytics/explorer/query_assist/hooks.ts
Do not display hidden indices in query assist index selector
=> (query assist) hide dot indices

public/components/integrations/components/integration.tsx
If a user tries to access a nonexistent integration template, they get no UI. This causes a display bug if the user adds a template, creates an instance with the template, deletes the template, and tries to navigate to it. This PR adds minimal handling to send an error message and redirect to the full template list.
N/A
=> Add redirect with error message if integrations template not found

public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap, public/components/common/search/search.tsx, public/components/common/search/sql_search.tsx, public/components/event_analytics/explorer/datasources/datasources_selection.tsx
Prompt user with modal explaining selecting DQL will lead them being redirected to Discover.
=> Add modal for DQL language

public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/sidebar/sidebar.scss
this styling is affecting discover, and as they are changing the styling, we are for now just change the name to decouple
`.deSidebar {
height: calc(100vh - 98px);
max-width: 462px;
min-width: 400px;
}`
=> Change class name to decouple styling from discover

release-notes/dashboards-observability.release-notes-2.12.0.0.md
Add release notes for 2.12.0
* Relate https://github.com/opensearch-project/dashboards-observability/issues/1104
=> Add release notes for 2.12.0

.cypress/integration/panels_test/panels.spec.ts, public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap, public/components/custom_panels/__tests__/custom_panel_table.test.tsx, public/components/custom_panels/__tests__/custom_panel_view.test.tsx, public/components/custom_panels/__tests__/custom_panel_view_so.test.tsx, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/helpers/__tests__/add_visualization_helper.test.ts, public/components/custom_panels/helpers/__tests__/utils.test.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout_so.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/visualization_flyout_so.test.tsx, test/panels_constants.tsx
Reopening to trigger code coverage bot
* Improves Jest test coverage for components under the `custom_panels` directory
* Fixes flaky Cypress tests
#201 #1278
=> [MAINTENANCE] Improving Jest Test Coverage for Observability Dashboards and Fixing Cypress Tests 

.cypress/integration/panels_test/panels.spec.ts, public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap, public/components/custom_panels/__tests__/custom_panel_table.test.tsx, public/components/custom_panels/__tests__/custom_panel_view.test.tsx, public/components/custom_panels/__tests__/custom_panel_view_so.test.tsx, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/helpers/__tests__/add_visualization_helper.test.ts, public/components/custom_panels/helpers/__tests__/utils.test.tsx, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout_so.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/visualization_flyout_so.test.tsx, test/panels_constants.tsx
* Manual backport for #1409, cherry picking 1211e83.
* Commit message on 0402b04 is a typo, should be 1211e83.
* Test for `fetchAggregatedBins()` was removed since it doesn't exist in `2.x`.
#201 #1278
=> [Backport 2.x] Backporting #1409 Panels Tests Updates

public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.scss, public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx, public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
Rename overriding styles that were perviously borrowed from the core dashboards as it is now causing style overriding issue in visBuilder.
Before
After
=> [BUG] Fixing style overriding issue in dashboards core vizBuilder

common/types/trace_analytics.ts, public/components/trace_analytics/components/traces/flyout_list_item.tsx, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, public/components/trace_analytics/requests/traces_request_handler.ts
- make tag.error optional
- use correct field names when filtering spans
=> Fix jaeger spans key names for filtering

.github/workflows/dashboards-observability-test-and-build-workflow.yml, .github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml, .github/workflows/lint.yml, public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap
- On behalf of the change in dashboards core: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5675. We need to add `--single-version=loose` flag during the bootstrap step in our CI to manipulate the behavior of single-version validation. 
- Fix the snapshot mismatch with upstream
* Resolve the CI failure: https://github.com/opensearch-project/dashboards-observability/actions/runs/7964135017/job/21741091909?pr=1447#step:16:231
=> [CI/CD] Add single version flag during bootstrap to fix version conflicts and update the snapshots

.github/workflows/dashboards-observability-test-and-build-workflow.yml, .github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml, .github/workflows/lint.yml
Add single version flag during bootstrap to fix version conflicts
* Backport #1454 
=> [Backport 2.x] Add single version flag during bootstrap to fix version conflicts

public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx, public/components/event_analytics/explorer/query_assist/input.tsx
Currently we use summarization to explain PPL errors, but it won't be available if summarization feature is disabled. This PR enables sending error to toast message in that case.
=> (query assist) show error toasts if summary is disabled

public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/manage/data_connection.tsx
Remove index store region and index store URI for data connection panel
=> [Feature] Remove index store region and index store URI for data connection panel

server/index.ts, server/plugin.ts, server/routes/index.ts, server/routes/query_assist/routes.ts, server/routes/query_assist/utils/__tests__/agents.test.ts, server/routes/query_assist/utils/agents.ts, server/routes/query_assist/utils/constants.ts
This PR does the similar thing as https://github.com/opensearch-project/dashboards-assistant/commit/a3560318a94ec36c26e3fab23780730fb82dcfbf. Instead of setting these in config yml 
```yml
observability.query_assist.ppl_agent_name: "PPL agent"
observability.query_assist.response_summary_agent_name: "Response summary agent"
observability.query_assist.error_summary_agent_name: "Error summary agent"
```
users should send the following request as superadmin:
```http
PUT /.plugins-ml-config/_doc/os_query_assist_ppl
{
"type":"os_query_assist_ppl_agent",
"configuration":{
"agent_id": "your ppl agent id"
}
}
PUT /.plugins-ml-config/_doc/os_query_assist_response_summary
{
"type":"os_query_assist_response_summary_agent",
"configuration":{
"agent_id": "your response summary agent id"
}
}
PUT …
```
=> (query assist) get agent id through config API

common/constants/data_sources.ts, common/constants/shared.ts, common/types/data_connections.ts, common/utils/query_session_utils.ts, common/utils/shared.ts, public/components/common/search/direct_search.tsx, public/components/event_analytics/explorer/datasources/datasources_selection.tsx, public/framework/catalog_cache/cache_intercept.ts, public/framework/catalog_cache/cache_loader.test.tsx, public/framework/catalog_cache/cache_loader.ts, public/framework/catalog_cache/cache_loader.tsx, public/framework/catalog_cache/cache_manager.test.tsx, public/framework/catalog_cache/cache_manager.ts, public/plugin.tsx, public/services/saved_objects/saved_object_loaders/explorer_saved_object_loader.ts, test/datasources.ts
Catalog cache and Session update for async queries
#1484 
#1251 
=> Catalog cache and Session update for async queries

.github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml, opensearch_dashboards.json, package.json
Bump plugin version to 2.13.0 and automated the version fetching in workflows
* The CI failure on 2.x: https://github.com/opensearch-project/dashboards-observability/actions/runs/8192762404/job/22405015049#step:18:10
=> [Maintenance] Bump plugin version to 2.13.0

public/components/integrations/components/__tests__/__snapshots__/added_integration_table.test.tsx.snap, public/components/integrations/components/added_integration_table.tsx, public/components/integrations/components/integration.tsx
Updating some headers after UI review.
N/A
=> Minor integration name updates

common/types/data_connections.ts, public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap, public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/__tests__/associated_objects_flyout.test.tsx, public/components/datasources/components/__tests__/associated_objects_tab.test.tsx, public/components/datasources/components/__tests__/data_connection.test.tsx, public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx, public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx, public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx, public/plugin.tsx
Manual backport of #1496: Add flyout pages to associated objects table.
* Backport #1496 
=> [Backport 2.x] Add flyout pages to associated objects table

common/constants/data_connections.ts, public/components/datasources/components/__tests__/data_connection.test.tsx, public/components/datasources/components/manage/accelerations/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap, public/components/datasources/components/manage/accelerations/create/__tests__/__snapshots__/create_acceleration_header.test.tsx.snap, public/components/datasources/components/manage/accelerations/create/__tests__/create_acceleration.test.tsx, public/components/datasources/components/manage/accelerations/create/create_acceleration.tsx, public/components/datasources/components/manage/accelerations/selectors/__tests__/__snapshots__/source_selector.test.tsx.snap, public/components/datasources/components/manage/accelerations/selectors/__tests__/source_selector.test.tsx, public/components/datasources/components/manage/accelerations/selectors/index_type_selector.tsx, public/components/datasources/components/manage/accelerations/selectors/source_selector.tsx, public/components/datasources/components/manage/data_connection.tsx, public/plugin.tsx
* Expose create acceleration flyout so dependent plugins can use it. 
* Update accelerations documentation link 
* Update onclick functions for the EUI cards in data connections tab 
Follow-up on: #1508 
=> Expose create acceleration flyout, update acceleration docs link

common/types/data_connections.ts, public/framework/catalog_cache/cache_loader.test.tsx, public/framework/catalog_cache/cache_loader.tsx, public/framework/catalog_cache/cache_manager.test.tsx, public/framework/catalog_cache/cache_manager.ts
Updating the accelerations cache structure from:
```
export interface CachedAccelerations {
flintIndexName: string;
type: AccelerationIndexType;
database: string;
table: string;
indexName: string;
autoRefresh: boolean;
status: string;
}
export interface AccelerationsCacheData {
version: string;
accelerations: CachedAccelerations[];
lastUpdated: string; // date string in UTC format
status: CachedDataSourceStatus;
}
```
To:
```
export interface CachedAccelerations {
flintIndexName: string;
type: AccelerationIndexType;
database: string;
table: string;
indexName: string;
autoRefresh: boolean;
status: string;
}
export interface CachedAcclerationByDataSource {
name: string;
accelerations: CachedAccelerations[];
lastUpdated: string; // date string in UTC format
status: CachedDataSourceStatus;
} …
```
=> Add datasource field in accelerations cache

public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/__tests__/setup_integration.test.tsx, public/components/integrations/components/create_integration_helpers.ts, public/components/integrations/components/setup_integration.tsx, server/adaptors/integrations/__data__/repository/aws_elb/aws_elb-1.0.0.json, server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json, server/adaptors/integrations/__data__/repository/nginx/nginx-1.0.0.json, server/adaptors/integrations/__test__/builder.test.ts, server/adaptors/integrations/integrations_adaptor.ts, server/adaptors/integrations/integrations_builder.ts, server/adaptors/integrations/integrations_manager.ts, server/adaptors/integrations/repository/integration_reader.ts, server/adaptors/integrations/types.ts, server/adaptors/integrations/validators.ts, server/routes/integrations/integrations_router.ts, test/constants.ts
Adds rudimentary support for toggling some parts of the integration installation process. There's still some parts that need to be updated:
Closes #1462 
=> Add conditional installation for S3 integrations

common/constants/query_assist.ts, public/components/common/search/query_area.scss, public/components/common/search/query_area.tsx, public/components/common/search/search.tsx, public/components/event_analytics/explorer/log_patterns/log_patterns.tsx, public/components/event_analytics/explorer/no_results.tsx, public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx, public/components/event_analytics/explorer/query_assist/input.tsx, public/components/event_analytics/redux/slices/query_assistant_summarization_slice.ts, server/routes/query_assist/routes.ts
- styling change to query assist
- move NLQ input above query textarea
- wrap component in collapsible accordion
- merge `Generate query` and `Generate and run` into a split button
- update wording
- guardrail support: display error callout if guardrail is triggered
=> Update UI styles for query assist

public/components/common/search/search.tsx
Removal of modal for indicating user the redirection to Discover upon DQL clicked in language selector.
=> [Log explorer] Remove modal for discover redirection

public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/setup_integration.tsx
Updates the text for the integration workflow selection to show selecting resources, per UX feedback.
N/A
=> Copy Updates: Integration Flows -> Integration Resources

common/types/data_connections.ts, public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap, public/components/datasources/components/__tests__/acceleration_table.test.tsx, public/components/datasources/components/__tests__/associated_objects_flyout.test.tsx, public/components/datasources/components/__tests__/associated_objects_tab.test.tsx, public/components/datasources/components/manage/accelerations/acceleration_table.tsx, public/components/datasources/components/manage/accelerations/flyout_modules/accelerations_schema_tab.tsx, public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx, public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx, public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx, public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx, public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_utils.tsx, public/plugin.tsx, public/types.ts, test/datasources.ts
* Links `Create Acceleration` flyout to:
1. Accelerations tab `Create Acceleration` button
2. Lightning bolt icon in associated objects table
3. Lightning bolt icon in associated object detail flyout
4. `Create Acceleration` button in associated object detail flyout when there are no accelerations
* Add loading to cache for table columns
* Display associated accelerations in associated object table
* Miscellaneous string and typing updates
N/A
=> Data Sources component Improvements and bug fixes

common/utils/shared.ts, public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap, public/components/datasources/components/__tests__/installed_integrations_table.test.tsx, public/components/datasources/components/manage/data_connection.tsx, public/components/datasources/components/manage/integrations/installed_integrations_table.tsx, public/components/integrations/components/__tests__/__snapshots__/available_integration_card_view.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/available_integration_table_view.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/__tests__/testing_constants.ts, public/components/integrations/components/available_integration_card_view.tsx, public/components/integrations/components/available_integration_overview_page.tsx, public/components/integrations/components/available_integration_table.tsx, public/components/integrations/components/integration_header.tsx, public/framework/core_refs.ts, test/constants.ts
As part of in-progress work for allowing integration installation in a Flyout, this PR does the first step of copying the integration browsing component to the Flyout, with some additional refactoring for the changes (mostly around how category filters are rendered).
N/A
=> Allow browsing integrations in Flyout from Data Sources page

common/constants/shared.ts, common/types/data_connections.ts, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/create_acceleration.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/utils.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/utils.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/preview_sql_defintion.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/source_selector.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/preview_sql_defintion.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/source_selector.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/preview_sql_defintion.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_databases.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_objects.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/source_selector.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/__tests__/__snapshots__/query_visual_editor.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/__snapshots__/generate_fields.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/__snapshots__/skipping_index_builder.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/__tests__/generate_fields.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/generate_fields.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/skipping_index/skipping_index_builder.tsx, public/framework/core_refs.ts, public/framework/datasources/direct_query_hook.tsx, public/plugin.tsx, public/types.ts
Add auto-suggestions for skipping index definition and export types
1. Generate suggestions for skipping index
2. Check plugin status to show open in workbench button
3. Export CacheManager for usage in query workbench
=> Add auto-suggestions for skipping index definition and export types

.cypress/integration/integrations_test/integrations.spec.js, public/components/common/helpers/delete_modal.tsx, public/components/integrations/components/added_integration.tsx, public/components/integrations/components/added_integration_table.tsx
Per UX: the delete modal uses in general should be using some variable text instead of a fixed "delete". This PR updates the DeleteModal component with an optional prompt that's used for deletion (defaulting back to "delete"), and activates this prompt within Integrations.
N/A
=> Integrations: Update delete modal to support custom verify prompt

public/components/common/search/direct_search.tsx, public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap, public/components/event_analytics/explorer/events_views/data_grid.tsx, public/components/event_analytics/explorer/explorer.tsx
- For s3 data sources, disabled sorting
- Disabled autocomplete for s3 ppl
- For s3, implemented basic working pagination
- In default data sources: Explorer data grid fix flyout after sort correspond to correct row
- Fix/reenable surrounding events
- Create ability for surrounding events to work on s3
=> Fixed small bugs in explorer

public/components/common/query_utils/index.ts, public/components/common/search/date_picker.tsx, public/components/common/search/search.tsx, public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap, public/components/event_analytics/explorer/__tests__/data_grid.test.tsx, public/components/event_analytics/explorer/events_views/data_grid.tsx, public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/no_results.tsx, public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_configurations_panel.tsx, public/services/data_fetchers/ppl/ppl_data_fetcher.ts, public/services/saved_objects/saved_object_loaders/explorer_saved_object_loader.ts
To allow for querying of flint materialized views and covering indices which may not have timestamps, Explorer is being extended to show results from queries with no timestamps
Changes:
- Check field mapping for no timestamp
- Send out query without timestamp and get results to Explorer
- Disable timepicker
- Get rid of time column in data grid
- Saved query: modify load
- Visualization changes
- Disable patterns
- Enable Hit Counter
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifi …
=> Implement results from no timestamp in Explorer

public/components/event_analytics/explorer/log_explorer.scss, public/components/event_analytics/explorer/no_results.tsx
=> add info callout for s3 datasources

public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_type_selector.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_type_selector.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_databases.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/selector_helpers/load_objects.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/query_visual_editor.tsx
Update loading state for tables fields in create acceleration flyout
1. Reset fields in acceleration create workflow when fields change
2. Update loading state to be in definitions instead of flyout
3. On unmount stop loaders
=> Update loading state for tables fields in create acceleration flyout

public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap, public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/__tests__/acceleration_table.test.tsx, public/components/datasources/components/manage/accelerations/acceleration_action_overlay.tsx, public/components/datasources/components/manage/accelerations/acceleration_table.tsx, public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx, public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx, public/components/datasources/components/manage/data_connection.tsx
Flint datasource 2.13 bug bash fix
- Align the font with AO table
- Acceleration table's status column capitalization issue.
- Acceleration table header and buttons formatting.
- Acceleration table timestamp localization.
- "Query in Observability Logs" instead of "Query in Discover" for Get Started box in data connection.
- Fix the discover icons description in both acceleration table and associated table.
=> [Bug Fix] Flint datasource 2.13 bug bash fix

public/components/datasources/components/__tests__/__snapshots__/installed_integrations_table.test.tsx.snap, public/components/datasources/components/manage/integrations/installed_integrations_table.tsx, public/components/integrations/components/setup_integration.tsx
Disables the ability to close the integration install flyout when an integration is being installed.
N/A
=> Disable close button when integration is being installed

public/components/event_analytics/explorer/__tests__/__snapshots__/data_grid.test.tsx.snap
https://github.com/opensearch-project/dashboards-observability/pull/1533 -> PR fixed test snapshots on main but somehow got trickled down to 2.x and 2.13 restoring older snapshots as this is not backported to core yet. 
* Restore explorer datagrid snapshots
=> Fix datagrid snapshots for 2.x 

public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap, public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx, public/components/datasources/components/manage/associated_objects/utils/associated_objects_tab_empty.tsx, public/components/hooks/use_polling.ts
* A simpler fix that achieves the same thing as #1586 
* When the component that initializes `usePolling()` unmounts before `stopPolling()` is called, it causes the `setInterval` to become a zombie process in the background. Updated the hook such that we check if unmounted before exiting the `startPolling()` function and clear if true.
* Updated UI for empty state
* Allow failed cache state to start reloading
N/A
=> Updating usePolling to cleanup after unmount

common/constants/data_sources.ts, public/components/common/search/direct_search.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration_button.tsx
Sanitize queries which have a potential for users to add in a `\n`, `\t` or extra white spaces
1. Sanitize direct queries from explorer
2. Sanitize direct queries from create acceleration flyout
=> Sanitize create acceleration queries and direct queries

docs/integrations/README.md, docs/integrations/config.md, docs/integrations/setup.md
It ain't much, but it's honest work.
Adds some basic documentation for the setup process and config files for integrations.
Part of #730, though that specific issue may need to be redone a bit for the modern integrations landscape.
=> Add basic developer docs for integration setup and config

public/components/event_analytics/explorer/query_assist/input.tsx, server/routes/dsl.ts
* In this [PR](https://github.com/opensearch-project/dashboards-observability/pull/1521/files#diff-1f9448392ecc6df0b6d0408be8f0fc5220624ca9d18b4303c0c49bf6313978d9R55), `cat.indices` is validated to have a `format` field and `index` field. Since `cat.indices` does not require an `index` field, I changed it to a maybe so that it doesn't break other components that call this API.
* When query assist successfully generates PPL, display a callout.
* Remove return button next to query assist input field.
https://github.com/opensearch-project/dashboards-observability/assets/47805161/f649b704-bac5-4a53-ac80-619f18fd5bf3
N/A
For more information on following Developer Certificate of …
=> Fix DSL router, update UI for query assist

common/types/data_connections.ts, opensearch_dashboards.json, public/components/datasources/components/__tests__/__snapshots__/associated_objects_tab.test.tsx.snap, public/components/datasources/components/manage/accelerations/acceleration_action_overlay.tsx, public/components/datasources/components/manage/accelerations/acceleration_table.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration_button.tsx, public/components/datasources/components/manage/accelerations/utils/acceleration_utils.tsx, public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx, public/components/datasources/components/manage/associated_objects/associated_objects_tab.tsx, public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx, public/plugin.tsx, public/types.ts, test/datasources.ts
* Adds try catch for fetching tables
* Updates `Accelerations` columns to `Associations` for better visibility
* Skipping indices and covering indices have their associated table listed now
N/A
=> Bug fixes and UI updates for datasources

common/constants/query_assist.ts, opensearch_dashboards.json, public/components/event_analytics/explorer/query_assist/input.tsx, server/routes/query_assist/routes.ts
Catch for guardrails was added in #1523, but seems to not work as `error.body.error` is undefined because `error.body` is a string. 
```
ResponseError: Response Error
at onBody (/Users/lnse/opensearch/OpenSearch-Dashboards/node_modules/@opensearch-project/opensearch/lib/Transport.js:426:23)
at IncomingMessage.onEnd (/Users/lnse/opensearch/OpenSearch-Dashboards/node_modules/@opensearch-project/opensearch/lib/Transport.js:341:11)
at IncomingMessage.emit (node:events:525:35)
at IncomingMessage.emit (node:domain:489:12)
at endReadableNT (node:internal/streams/readable:1359:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21) {
meta: {
body: '{"error":{"reason":"Invalid Request","details":"guardrails triggered for user …
```
=> Updating catch for guardrails

public/framework/catalog_cache/cache_intercept.ts
Clear cache on any 401 response errors
https://github.com/opensearch-project/dashboards-observability/issues/1484
=> Clear cache on any 401 response errors

server/adaptors/integrations/repository/integration_reader.ts
Integration data assets are JSON stringified before being serialized, which means that they get sent escaped to further endpoints. This breaks the query API usage. This PR removes the extra escape.
TODO: Tests to catch this in the future.
Big props to @seankao-az for setting up the infra to test the functionality and find this
N/A
=> [BUGFIX] Fix integration data reading double escape

public/components/datasources/components/manage/data_connection.tsx, public/components/datasources/components/manage/integrations/installed_integrations_table.tsx, public/components/integrations/components/setup_integration.tsx
So after getting a test instance (further context: #1643), there were More Problems. This fixes the flyout installation when an install actually succeeds. Before, the install would eternally show a loading screen while silently succeeding in the background. Now the flyout is auto-closed on success.
TODO: More tests
N/A
=> Fix integration flyout successes

public/components/event_analytics/explorer/query_assist/input.tsx
Dismissible flag in callouts is buggy in query assist, so to update the UI, we should clear the callout once user starts to type another query.
N/A
=> Clear callout in query assist 

public/framework/catalog_cache/cache_intercept.ts, public/plugin.tsx
Update intercept to check logout request
The Earlier intercept was not being triggered as it was being run after the security dashboards intercept on responseError. 
Hence, moving to intercept requests to catch the logout action from user to clear cache. 
Security plugin intercept: https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/utils/logout-utils.tsx
Old Observability plugin intercept: https://github.com/opensearch-project/dashboards-observability/blob/main/public/framework/catalog_cache/cache_intercept.ts
OSD response error intercepts code: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2a94f32dc332f097ca447fd15887d346415fafdf/src/core/public/http/intercept.ts#L86
By submitting this pull request, I confirm that my contribution is made …
=> Update intercept to check logout request

public/components/datasources/components/manage/associated_objects/modules/associated_objects_table.tsx
On some edge cases where databases and accelerations are loaded at the same time, some associated objects could have undefined accelerations/associations. This PR checks if the association is defined first before displaying.
N/A
=> Bug Fix for Undefined Association

public/components/datasources/components/manage/associated_objects/associated_objects_details_flyout.tsx
Previously, updating the cache in the tables flyout doesn't update it in the associated objects array. Fix by checking cache before loading schema.
N/A
=> Correctly Utilize Cache in Tables Flyout

public/framework/catalog_cache/cache_manager.test.tsx, public/framework/catalog_cache/cache_manager.ts
Convert cache to session storage
This PR helps to reduce the lifecycle of the catalog cache to be limited to a browser's tab lifecycle. 
=> Convert cache to session storage

opensearch_dashboards.json, public/plugin.tsx, public/types.ts
* prevent logged out datasources call
Signed-off-by: Paul Sebastian <paulstn@amazon.com>
* check if security plugin is installed
Signed-off-by: Paul Sebastian <paulstn@amazon.com>
* clean up logic
Signed-off-by: Paul Sebastian <paulstn@amazon.com>
* include a catch clause to register datasources when account api has non 401 error
Signed-off-by: Paul Sebastian <paulstn@amazon.com>
* included comment
Signed-off-by: Paul Sebastian <paulstn@amazon.com>
---------
Signed-off-by: Paul Sebastian <paulstn@amazon.com>
(cherry picked from commit c14c3f813c43bc296e1ded355a5b7e9bd425869b)
For more information on …
=> [Backport 2.x] prevent logged out datasources call (#1653)

public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap, public/components/common/search/date_picker.tsx, public/components/common/search/query_area.tsx, public/components/common/search/search.tsx, public/components/event_analytics/explorer/query_assist/__tests__/__snapshots__/callouts.test.tsx.snap, public/components/event_analytics/explorer/query_assist/__tests__/callouts.test.tsx, public/components/event_analytics/explorer/query_assist/__tests__/input.test.tsx, public/components/event_analytics/explorer/query_assist/callouts.tsx, public/components/event_analytics/explorer/query_assist/input.tsx
- make callouts dismissable, auto dismiss on question or query change
- change style of single selection in combo box
- remove date picker if query assist is enabled
=> (query assist) update styles for callout and combo box

public/components/common/search/autocomplete.tsx, public/components/common/search/direct_search.tsx, public/components/common/search/search.tsx, public/components/event_analytics/explorer/no_results.tsx
Fixes:
- Typo with SHOW TABLES query -> SHOW TABLE
- unexpected behavior where the autocomplete component's shift enter listener populates the ran query as something stale, for direct queries
- non direct query updates everything needed now
=> fix small issues within explorer search bar and sample query

server/adaptors/integrations/__data__/repository/aws_waf/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_waf/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.0.0.json
=> [Integrations] Add integration of WAF log

server/adaptors/integrations/__data__/repository/aws_s3/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_s3/assets/create_table-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_s3/aws_s3-1.0.0.json
Add integration of S3 Access log
=> [Integrations] Add integration of S3 Access log

common/constants/data_sources.ts, common/types/data_connections.ts, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/__snapshots__/create_acceleration.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/__tests__/utils.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/create_acceleration.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/create/utils.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/__snapshots__/index_setting_options.test.tsx.snap, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/__tests__/index_setting_options.test.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/selectors/index_setting_options.tsx, test/accelerations.ts
Remove auto refresh option, update tests
1. Remove auto refresh option without interval
2. Set minimum refresh time as 15 mins
3. Update tests
=> Remove auto refresh option in create acceleration flyout

opensearch_dashboards.json, package.json, server/adaptors/integrations/__data__/repository/apache/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudfront/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_elb/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_s3/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_waf/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/haproxy/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql
- Add default refresh interval for all the integrations, and limit it to `15 Minute` as default.
- Correct the version on `main`
For VPC integration still awaiting on PR: https://github.com/opensearch-project/dashboards-observability/pull/1691 (cc: @YANG-DB )
=> [Integrations] Add default refresh interval for all the integrations and correct the version on `main`

server/adaptors/integrations/__data__/repository/apache/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudfront/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_elb/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_s3/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_waf/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/haproxy/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql
Add default refresh interval for all the integrations
* Backport #1717 
=> [Manual Backport 2.x] Add default refresh interval for all the integrations

server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_live_all_mv-1.0.0.sql
Set up a default refresh interval for VPC integration's MV
* Relate https://github.com/opensearch-project/dashboards-observability/pull/1721
=> [Forward port] Set up a default refresh interval for VPC integration's MV

server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_live_all_mv-1.0.0.sql
Fix VPC live MV table name
Two live tables share the same name
=> update live mv table name

public/components/datasources/components/__tests__/__snapshots__/data_connection.test.tsx.snap, public/components/datasources/components/__tests__/data_connection.test.tsx, public/components/datasources/components/manage/data_connection.tsx
Add conditional rendering for data connection page's tabs
* Relate https://github.com/opensearch-project/dashboards-observability/issues/1666
=> [Bug fix] Add conditional rendering for data connection page's tabs

public/components/custom_panels/helpers/utils.tsx
fix parsing but [object Object] is not valid JSON in prometheus metrics
#1665
=> fix prometheus response parsing issue 

public/plugin.tsx
Fix `S3_DATASOURCE_TYPE` naming typo in `plugin.tsx`
```
Version: 2.13.0
Build: 9007199254740991
ReferenceError: S3_DATA_SOURCE_TYPE is not defined
at ObservabilityPlugin.start (http://0.0.0.0:5601/9007199254740991/bundles/plugin/observabilityDashboards/observabilityDashboards.plugin.js:370683:46)
at PluginWrapper.start (http://0.0.0.0:5601/9007199254740991/bundles/core/core.entry.js:28328:47)
at PluginsService.start (http://0.0.0.0:5601/9007199254740991/bundles/core/core.entry.js:28704:25)
at async CoreSystem.start (http://0.0.0.0:5601/9007199254740991/bundles/core/core.entry.js:22094:7)
at async Module.__osdBootstrap__ (http://0.0.0.0:5601/9007199254740991/bundles/core/core.entry.js:27045:17)
```
* Introduced by https://github.com/opensearch-project/dashboards-observability/pull/1752
By …
=> [BugFix] Fix `S3_DATASOURCE_TYPE` naming typo in `plugin.tsx`

public/components/event_analytics/explorer/log_explorer.tsx
Query assist enabled variable will gets reloaded based on http response telling whether PPL agent is configured. The time range usually sets before the response returns, which makes the time range to be last 40 years if query assist is enabled but not configured. Since time range picker is removed from UI, this logic can also be removed.
=> remove defaulting to query assist time range

server/routes/data_connections/data_connections_router.ts
/api/dataconnections API is failing with 404 due to changes introduced from this [change](https://github.com/opensearch-project/dashboards-observability/commit/fdf2808f515f87d03068412f73b4b884296615ea#diff-ffbf68401b3813188bc809411d7b447f47dbefcc686286394a00c910bcc78c64L48):  this PR fix this issue.
=> Fix data connection api 404 error

public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/materialized_view/column_expression.tsx, public/components/datasources/components/manage/accelerations/create_accelerations_flyout/visual_editors/query_builder.tsx, test/accelerations.ts
(cherry picked from commit c7ee338cd882f0787e1537bc3924901682df085f)
Fix window start backtick during MV creation
#1819 
=> Fix window start backtick during MV creation

server/adaptors/integrations/__data__/repository/otel-services/schemas/traces-1.0.0.mapping.json
Attributes fields is missing properties making the rest of the fields in the same level as main properties of the index
=> Fix traces index schema bug

.github/ISSUE_TEMPLATE/integration_request.md, .lycheeignore, README.md, public/components/notebooks/docs/dev/Build_Documentation.md, public/components/notebooks/docs/dev/OpenSearch-Dashboards-Notebooks-Design-Proposal.md, public/components/notebooks/docs/dev/Usage_Documentation.md, server/adaptors/integrations/__data__/repository/amazon_elb/info/INGESTION.md, server/adaptors/integrations/__data__/repository/amazon_elb/info/README.md, server/adaptors/integrations/__data__/repository/amazon_rds/assets/README.md, server/adaptors/integrations/__data__/repository/amazon_rds/info/README.md, server/adaptors/integrations/__data__/repository/amazon_s3/info/README.md, server/adaptors/integrations/__data__/repository/amazon_vpc_flow/assets/README.md, server/adaptors/integrations/__data__/repository/otel-services/info/DemoLandingPage.md
Fixes dead links for the Lychee link checker. This isn't a lossless conversion:
- Where possible, outdated links were updated.
- Some links seemed fully defunct, these were removed outright, sometimes involving deleting docs sections that seemed outdated. e.g. many of the Zeppelin doc links and several links in the OTEL services integration.
- Example links (to OSD instances or in one case to a local k8s cluster) were added to the lycheeignore rules.
- There's also a playground link that causes a "too many redirects" error and also was ignored.
N/A …
=> Fix dead links

public/components/integrations/components/__tests__/__snapshots__/integration_details.test.tsx.snap, public/components/integrations/components/integration_details_panel.tsx
Adds a 'check for version' link that directs the user to the releases page for opensearch-catalog. This makes it easier to discover new content, without users needing to know ahead of time that the catalog exists. (To do: make this dynamic so external integration authors can insert their own links.)
Before:
After:
N/A
=> Add 'check for version' link in the integration details page

public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/metrics/helpers/utils.tsx, public/components/metrics/index.tsx, public/components/metrics/redux/slices/metrics_slice.ts, public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/metrics/sidebar/sidebar.tsx, public/components/metrics/top_menu/metrics_export.tsx, public/components/metrics/view/metrics_grid.tsx, public/services/requests/ppl.ts, server/adaptors/metrics/metrics_analytics_adaptor.ts, server/routes/data_connections/data_connections_router.ts, server/routes/index.ts, server/routes/metrics/metrics_rounter.ts, server/routes/ppl.ts, server/services/facets/ppl_facet.ts
With multiple data source enabled, users of OpenSearch Dashboards with Metrics analytics are able to fetch metrics from local and remote clusters
MDS support for metrics analytics
https://github.com/opensearch-project/dashboards-observability/issues/1754
=> added supoort for metrics MDS

public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap, public/components/integrations/components/__tests__/setup_integration_inputs.test.tsx, public/components/integrations/components/setup_integration.tsx, public/components/integrations/components/setup_integration_inputs.tsx, server/adaptors/integrations/__data__/repository/amazon_vpc_flow/amazon_vpc_flow-1.1.0.json, server/adaptors/integrations/types.ts, server/adaptors/integrations/validators.ts
Manual backport of #1868 to 2.x
N/A
=> Add applicable_data_sources field to workflows definition

public/components/trace_analytics/components/common/plots/__tests__/__snapshots__/service_map_scale.test.tsx.snap, public/components/trace_analytics/components/common/plots/service_map_scale.tsx, public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap, public/components/trace_analytics/components/services/services_table.tsx, public/components/trace_analytics/home.tsx
* Update the theming in dark mode for scale of the service map
* Add data test-subj for cypress
* Update truncate usage to use imported lodash
* Add mode dependency to attributefilter useEffect
* update test snapshots
https://github.com/opensearch-project/dashboards-observability/issues/1820
=> [Backport 2.x] Minor bug fixes for trace analytics v2 (#1894)

public/components/custom_panels/helpers/utils.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/metrics/helpers/utils.tsx, public/components/metrics/index.tsx, public/components/metrics/redux/slices/metrics_slice.ts, public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/metrics/sidebar/sidebar.tsx, public/components/metrics/top_menu/metrics_export.tsx, public/components/metrics/view/metrics_grid.tsx, public/services/requests/ppl.ts, server/adaptors/metrics/metrics_analytics_adaptor.ts, server/routes/data_connections/data_connections_router.ts, server/routes/index.ts, server/routes/metrics/metrics_rounter.ts, server/routes/ppl.ts, server/services/facets/ppl_facet.ts
Manual backport of metrics https://github.com/opensearch-project/dashboards-observability/pull/1876
=> [Backport 2.x] Metrics analytics support for MDS 

common/constants/integrations.ts, public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/upload_flyout.test.tsx.snap, public/components/integrations/components/__tests__/upload_flyout.test.tsx, public/components/integrations/components/integration_details_panel.tsx, public/components/integrations/components/integration_header.tsx, public/components/integrations/components/upload_flyout.tsx
Adds the upload flyout for integrations, and also continues the work of #1863 in adding a catalog link.
https://github.com/opensearch-project/dashboards-observability/assets/31739405/fe61456d-a011-4847-8737-f0581cfd41d2
Closes #1867
=> Implement upload flyout for integrations

server/routes/query_assist/routes.ts
The two issues #509, #557 mentioned are still there, but PPL requires certain fields (i.e. fields with `@`) to be surrounded by backticks, otherwise there will be a syntax error. This PR reverts the behavior to allow those queries.
=> (query assist) revert removing backticks

release-notes/dashboards-observability.release-notes-2.15.0.0.md
Notes, generated with [my script](https://github.com/Swiddis/opensearch-utils/tree/main/release)
No notes
=> 2.15 release notes

public/components/metrics/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/metrics/sidebar/data_source_picker.tsx, release-notes/dashboards-observability.release-notes-2.15.0.0.md
Changed placeholder from data source to metric source
=> added placeholder change for metrics picker

public/components/datasources/components/new/configure_s3_datasource.tsx
Remove duplicate description for create s3 datasource flow
Before: 
After:
=> [Enhancement] Remove duplicate description for create s3 datasource flow

server/routes/data_connections/data_connections_router.ts, server/routes/dsl.ts, server/routes/index.ts
- add mds support for some routers
- Fix the missing `callAsCurrentUser` for router: `${DATACONNECTIONS_BASE}/dataSourceMDSId={dataSourceMDSId?}`
* Relate https://github.com/opensearch-project/dashboards-observability/pull/1876/files#diff-900935c25607c0c3c7a6febef66ca953de31ed6fcf234877c518bc8b6cf16269L226
=> [Bug Fix] Add mds support for routers and fix the missing `callAsCurrentUser`

common/utils/shared.ts, opensearch_dashboards.json, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap, public/components/metrics/index.tsx, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/notebooks/components/paragraph_components/paragraphs.tsx, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/trace_view.tsx, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/home.tsx
Add version decoupling meta data for MDS, a part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877
=> Version-decoupling for Observability

public/plugin.tsx
Unregister observability datasource from old and new nav group
* Relate https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7323
=> Unregister observability datasource from old and new nav group

release-notes/dashboards-observability.release-notes-2.16.0.0.md
=> Add 2.16 notes

package.json, public/components/common/search/__tests__/__snapshots__/search.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, release-notes/dashboards-observability.release-notes-2.16.0.0.md, yarn.lock
Fix CVEs for ag-grid, ws and braces packages
https://github.com/advisories/GHSA-328p-362g-r48j
https://github.com/advisories/GHSA-3h5v-q93c-6h6q
https://github.com/advisories/GHSA-328p-362g-r48j
=> Backport 2.x Fix CVEs for ag-grid, ws and braces packages

common/types/observability_saved_object_attributes.ts, release-notes/dashboards-observability.release-notes-2.16.0.0.md, server/saved_objects/observability_saved_object.ts
Url redirection fix for notebooks in Saved Objects Redirection 
=> [BUG] fix redirection url in saved objects management page for notebooks

public/components/application_analytics/home.tsx
(cherry picked from commit de8e0aa7f42f2643ccbbb16b7f3f6080cbe78254)
Fixes unable to load applications regression issue. More details in the original PR below. 
Backporting: https://github.com/opensearch-project/dashboards-observability/pull/1943
Issue: https://github.com/opensearch-project/dashboards-observability/issues/1931
=> [Backport main] Adding attributefilter field to app analytics (#1943)

public/components/getting_started/getting_started_artifacts/csv_file/csv_file-1.0.0.json, public/components/getting_started/getting_started_artifacts/golang_client/golang_client-1.0.0.json, public/components/getting_started/getting_started_artifacts/java_client/java_client-1.0.0.json
Update index patterns with the full qualified name
=> Fix docker links & index patterns names

public/components/application_analytics/components/application.tsx
the Traces and Span tab in application analytics was crashing as the MDS-ID was not being sent in to the traces page
https://github.com/opensearch-project/dashboards-observability/issues/1931
=> [BUG] Traces and Spans tab Fix for application analytics

public/components/trace_analytics/home.tsx, public/components/trace_analytics/trace_side_nav.tsx
Loading trace analytics directly via URL defaults to services page even when `/traces` path is added in the URL. 
Example: 
```
http://host:port/app/observability-traces#/services -> Loads services as expected.
http://host:port/app/observability-traces#/traces -> Doesn't load traces page, rather loads services page. 
``` 
Fixes the default route path when URL has the required hash and overrides the one in props. 
=> Fix direct url load for trace analytics

public/components/trace_analytics/home.tsx, public/components/trace_analytics/trace_side_nav.tsx
Loading trace analytics directly via URL defaults to services page even when `/traces` path is added in the URL. 
Main PR:  #2024
Example: 
```
http://host:port/app/observability-traces#/services -> Loads services as expected.
http://host:port/app/observability-traces#/traces -> Doesn't load traces page, rather loads services page. 
``` 
Fixes the default route path when URL has the required hash and overrides the one in props. 
=> [Backport 2.16] Fix direct url load for trace analytics

public/plugin_nav.tsx
Notebook is registered under analytics nav group by accident, this PR is to fix that. Notebook will still be visible under observability nav group.
=> [navigation]feat: remove useless registration of Notebook to analytics nav group

.github/CODEOWNERS, MAINTAINERS.md
Adding Ryan, Sean and Adam as dashboards-observability maintainers
PRs contributed by each of them to this repository is as mentioned below:
Ryan: https://github.com/opensearch-project/dashboards-observability/pulls?q=is%3Apr+author%3ARyanL1997
Sean: https://github.com/opensearch-project/dashboards-observability/pulls?q=is%3Apr+author%3Asejli
Adam: https://github.com/opensearch-project/dashboards-observability/pulls?q=is%3Apr+author%3Atackadam
=> Adding Ryan, Sean and Adam as dashboards-observability maintainers

public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/added_integration_flyout.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/integration_details.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/integration_header.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/setup_integration.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/setup_integration_inputs.test.tsx.snap, public/components/integrations/components/__tests__/__snapshots__/upload_flyout.test.tsx.snap, public/components/integrations/components/add_integration_flyout.tsx, public/components/integrations/components/added_integration.tsx, public/components/integrations/components/available_integration_table.tsx, public/components/integrations/components/integration.tsx, public/components/integrations/components/integration_details_panel.tsx, public/components/integrations/components/integration_header.tsx, public/components/integrations/components/integration_overview_panel.tsx, public/components/integrations/components/setup_integration_inputs.tsx, public/components/integrations/components/upload_flyout.tsx
This PR applies the Look & Feel density and consistency changes to the Integrations folder:
1. Use small context menus
2. Use small tabs
3. Standardize paragraph size (15.75px next theme / 14px V7 theme)
4. Use semantic headers (H1s on main pages, H2s on modals/flyouts)
5. Modal/Flyout Typography
6. Buttons for actions, only using primary buttons for primary calls to action
7. Use small padding on popovers
| Scope | Before | After |
| ----- | ----- | ----- |
| Integrations | <img width="794" alt="Integration Home context menu before" src="https://github.com/user-attachments/assets/2df09128-3c9f-46fc-9b34-0d000a5505e5"> | <img width="794" alt="Integration Home context menu post" src="https://github.com/user-attachments/assets/0c190355-d2c4-48cb-9b51-5178d5501b14"> |
| Scope | Before | …
=> [Look&Feel] Integrations Density and Consistency Improvements

public/components/application_analytics/__tests__/__snapshots__/create.test.tsx.snap, public/components/application_analytics/__tests__/__snapshots__/service_config.test.tsx.snap, public/components/application_analytics/__tests__/__snapshots__/trace_config.test.tsx.snap, public/components/metrics/top_menu/__tests__/__snapshots__/metrics_export.test.tsx.snap, public/components/metrics/top_menu/__tests__/__snapshots__/top_menu.test.tsx.snap, public/components/metrics/top_menu/metrics_export.tsx, public/components/trace_analytics/components/common/__tests__/__snapshots__/helper_functions.test.tsx.snap, public/components/trace_analytics/components/common/filters/filters.tsx, public/components/trace_analytics/components/common/helper_functions.tsx, public/components/trace_analytics/components/common/plots/service_map_node_details.tsx, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/dashboard_table.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_error_rates_table.test.tsx.snap, public/components/trace_analytics/components/dashboard/__tests__/__snapshots__/top_latency_table.test.tsx.snap, public/components/trace_analytics/components/dashboard/latency_trend_cell.tsx, public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services.test.tsx.snap, public/components/trace_analytics/components/services/__tests__/__snapshots__/services_table.test.tsx.snap, public/components/trace_analytics/components/services/service_trends_plots.tsx, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_flyout.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/span_detail_table.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces_table.test.tsx.snap, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, public/components/trace_analytics/components/traces/trace_view.tsx
This PR applies the Look & Feel density and consistency changes to Traces and Metrics:
1. Use small context menus
2. Use small tabs
3. Standardize paragraph size (15.75px next theme / 14px V7 theme)
4. Use semantic headers (H1s on main pages, H2s on modals/flyouts)
5. Modal/Flyout Typography
6. Buttons for actions, only using primary buttons for primary calls to action
7. Use small padding on popovers
| Scope | Before | After |
| ----- | ----- | ----- |
| Metrics | <img width="460" alt="Popover Before" src="https://github.com/user-attachments/assets/5920d5d4-fc47-471d-803b-65547b0a0ccb"> | <img width="460" alt="Popover Post" src="https://github.com/user-attachments/assets/3b42c5dc-9ce7-426b-a978-7987859bb52c"> |
| Scope | Before | After |
| ----- | ----- | ----- |
| Save | <img …
=> [Look&Feel] Traces Density and Consistency Improvements

.cypress/integration/notebooks_test/notebooks.spec.js, public/components/notebooks/components/__tests__/__snapshots__/note_table.test.tsx.snap, public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap, public/components/notebooks/components/helpers/__tests__/__snapshots__/modal_containers.test.tsx.snap, public/components/notebooks/components/helpers/custom_modals/__tests__/__snapshots__/custom_input_modal.test.tsx.snap, public/components/notebooks/components/helpers/custom_modals/custom_input_modal.tsx, public/components/notebooks/components/helpers/custom_modals/reporting_loading_modal.tsx, public/components/notebooks/components/helpers/modal_containers.tsx, public/components/notebooks/components/note_table.tsx, public/components/notebooks/components/notebook.tsx, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/para_output.test.tsx.snap, public/components/notebooks/components/paragraph_components/__tests__/__snapshots__/paragraphs.test.tsx.snap, public/components/notebooks/components/paragraph_components/para_input.tsx, public/components/notebooks/components/paragraph_components/para_output.tsx, public/components/notebooks/components/paragraph_components/paragraphs.tsx
This PR applies the Look & Feel density and consistency changes to Notebooks:
1. Use small context menus
2. Use small tabs
3. Standardize paragraph size (15.75px next theme / 14px V7 theme)
4. Use semantic headers (H1s on main pages, H2s on modals/flyouts)
5. Modal/Flyout Typography
6. Buttons for actions, only using primary buttons for primary calls to action
7. Use small padding on popovers
| Scope | Before | After |
| ----- | ----- | ----- |
| Notebook: Header Reporting | <img width="952" alt="Notebook Header Reporting Before" src="https://github.com/user-attachments/assets/f3d8e5f1-c465-4cfd-8d2d-9861479503dc"> | <img width="952" alt="Notebook Header Reporting Post" src="https://github.com/user-attachments/assets/01ba4d2d-e62c-45c7-bdec-58e3ac1db89c"> |
| Notebook: Header Paragraph | …
=> [Look&Feel] Notebooks Density and Consistency Improvements

public/components/custom_panels/__tests__/__snapshots__/custom_panel_table.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view_so.test.tsx.snap, public/components/custom_panels/custom_panel_table.tsx, public/components/custom_panels/custom_panel_view.tsx, public/components/custom_panels/custom_panel_view_so.tsx, public/components/custom_panels/helpers/__tests__/__snapshots__/custom_input_model.test.tsx.snap, public/components/custom_panels/helpers/add_visualization_popover.tsx, public/components/custom_panels/helpers/custom_input_modal.tsx, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_flyout/__tests__/__snapshots__/visualization_flyout_so.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout.tsx, public/components/custom_panels/panel_modules/visualization_flyout/visualization_flyout_so.tsx
This PR applies the Look & Feel density and consistency changes to the Observability Custom Panels Folder:
1. Use small context menus
2. Use small tabs
3. Standardize paragraph size (15.75px next theme / 14px V7 theme)
4. Use semantic headers (H1s on main pages, H2s on modals/flyouts)
5. Modal/Flyout Typography
6. Buttons for actions, only using primary buttons for primary calls to action
7. Use small padding on popovers
| Scope | Before | After |
| ----- | ----- | ----- |
| Dashboards: Overview Actions | <img width="795" alt="Dashboards Actions Before" src="https://github.com/user-attachments/assets/d6f2b6e5-d525-4817-a8e8-d1d0517cdef8"> | <img width="795" alt="Dashboards Post" src="https://github.com/user-attachments/assets/67413e5d-33c3-4f4a-b728-2251a2f3948b"> |
| Dashboards: Actions …
=> [Look&Feel] Custom Panels Density and Consistency Improvements

server/routes/query_assist/utils/__tests__/agents.test.ts, server/routes/query_assist/utils/agents.ts
update api handler to accommodate new ml-commons config response
addresses breaking change from https://github.com/opensearch-project/ml-commons/pull/2710
=> [query assist] update api handler to accommodate new ml-commons config response

public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/trace_view.tsx, public/components/trace_analytics/home.tsx, public/components/trace_analytics/trace_side_nav.tsx
Update trace analytics landing page to traces 
#2052 
Trace Analytics side nav change defaults to traces first
Before:
After:
Bug fix for header
Before:
After: 
Old nav: 
New nav: 
=> Update trace analytics landing page to traces and header bug fix 

server/routes/index.ts, server/routes/query_assist/routes.ts
update logic to process ml-commons response schema. `error.body` was a string before, now it is a JSON object. converting to string for backward compatibility
=> [query assist] update ml-commons response schema

.github/workflows/dashboards-observability-test-and-build-workflow.yml, .github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml
Update the actions/upload-artifact from v1 to v4
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> Update the actions/upload-artifact from v1 to v4

public/plugin.tsx, release-notes/opensearch-observability.release-notes-2.17.0.0.md
Add support for register plugin during the absence of local cluster
- Resolve the 500 errors when there is no backend plugins to consume the requests
=> [MDS] Add support for register data sources during the absence of local cluster

package.json, release-notes/opensearch-observability.release-notes-2.17.0.0.md, yarn.lock
Bump the lint-staged from 13.1.0 to 15.2.10
* CVE-2024-4067 
=> [CVE] Bump the lint-staged from 13.1.0 to 15.2.10

public/components/getting_started/components/getting_started_integrationCards.tsx
Today getting started plugin uses href to navigate to integrations plugin using the EuiCards for integrations catalog. This becomes an issue when `workspaces` is enabled in OSD core as workspaces relies on url in browser for saved object scoping. 
Removed the `href` call and replaced it with `navigateToApp` from core. 
=> Fix getting started cards re-direction to integrations

public/components/integrations/components/added_integration_table.tsx, public/components/integrations/components/available_integration_card_view.tsx
Latest Observability on 2.x/2.17 fails to load the integrations plugin due to import error. 
Fix integration imports for table and card view
* Updated loadash import
* Updated available integration type import
=> Fix integration imports for table and card view

public/plugin.tsx, release-notes/opensearch-observability.release-notes-2.17.0.0.md
Add support for register data sources during the absence of local cluster
- Resolve the 500 errors when there is no backend plugins to consume the requests
=> [Manual Backport 2.x] Add support for register data sources during the absence of local cluster

public/plugin.tsx
Rename the MDS feature flag variable to be more explicit
* Relate https://github.com/opensearch-project/dashboards-observability/pull/2140#discussion_r1747771582
=> [Main only] Rename the MDS feature flag variable to be more explicit

public/components/event_analytics/explorer/explorer.tsx, public/components/event_analytics/explorer/query_assist/input.tsx, public/components/event_analytics/hooks/use_fetch_events.ts
This PR has these fixes
- fix(log explorer): set loading state to false if query failed 
- this is a regression caused by https://github.com/opensearch-project/dashboards-observability/pull/1902
- update fetch call to pass in data source id 
- data source id is always undefined because log explorer doesn't support multi-datasource. passing undefined fixes the parameters so UI shows PPL errors in toasts
- revert icon to use prepend
- using `prepend` property the icon will be smaller than its original size, but since the text field is now `compact` and original size doesn't fit anymore, we can revert back to use `prepend`.
For more …
=> fix(log explorer): show PPL errors in toasts correctly

public/components/trace_analytics/components/common/__tests__/__snapshots__/search_bar.test.tsx.snap, public/components/trace_analytics/components/common/helper_functions.tsx, public/components/trace_analytics/components/common/plots/service_map.tsx, public/components/trace_analytics/components/common/search_bar.tsx, public/components/trace_analytics/components/traces/services_list.tsx, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/requests/queries/traces_queries.ts
Trace analytics UI bug fixes in custom sources
* Fix window scroll on top when selecting a filter from services list
* Fix refresh in traces page when search is made using "Shift+Enter"
* Updated service map empty state behaviour - on click load latency metrics
=> Trace analytics ui bug fixes in custom sources

server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-records-1.0.0.sql
Assets expect `userAgent`, not `aws.cloudtrail.userAgent`.
N/A
=> Fix cloudtrail field name mismatch

common/constants/trace_analytics.ts, common/types/trace_analytics.ts, public/components/application_analytics/components/application.tsx, public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap, public/components/trace_analytics/components/traces/trace_table_helpers.tsx, public/components/trace_analytics/components/traces/traces.tsx, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx, public/components/trace_analytics/home.tsx, public/components/trace_analytics/index.scss, public/components/trace_analytics/requests/queries/traces_queries.ts, public/components/trace_analytics/requests/traces_request_handler.ts
* The issue with original custom source table was that it says traces on top but shows data only from trace root spans. This is a problem cause it breaks users expectation of filtering traces across various fields like services and resource attributes. 
Sorting and Pagination push down won’t be part of this PR. 
Update custom traces table with filters added below:
* All Spans - All spans from all traces
* Traces - Aggregates all spans by traceId to show all traces
* Service Entry Spans - The spans that mark start of server-side processing (SPAN_KIND_SERVER)
* Trace Root Spans - The root spans which represent the starting point of a trace
Functional updates: 
* The trace table in custom source defaults to all spans
* The trace table mode is stored in session storage, to persist across tab …
=> Update custom traces table with filters

public/plugin_helpers/plugin_nav.tsx
Based on https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8332, observability needs to make some adjustment to flatten the menus in analytics(all) use case.
=> [navigation]feat: update category to flatten menus in analytics(all) use case

.github/workflows/dashboards-observability-test-and-build-workflow.yml, .github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml
The current cypress runs are failing with the error `Timeout for 600 seconds reached. OpenSearch Dashboards did not finish compiling.`. By far, the longest step of OSD startup is compilation. A little poking around upstream reveals that there's a script that can frontload this compilation, so we can separate the server startup from the compile step. This PR applies this, and lowers the timeout since it no longer needs to be so high. It also adds some caching to reduce build times, although there's a bit more that needs to happen to make build times fast (namely, caching all the /target folders, see #2188).
See above
For more information on following Developer Certificate of …
=> Add compile step before Cypress runs in CI

.github/workflows/dashboards-observability-test-and-build-workflow.yml, .github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml, public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap
Following https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8472 and #2188, this PR switches the cache to the actual build target directories to speed up caching dramatically.
Resolves #2188 
Avenges #925 
=> Update workflows to use real build cache

public/components/integrations/components/__tests__/__snapshots__/added_integration.test.tsx.snap, public/plugin.tsx, server/plugin.ts, server/saved_objects/observability_saved_object.ts
Remove PPL viz & create observability dashboards in MDS environment
PPL visualization option landed users on an empty page when MDS is enabled. We removed this option when MDS is enabled to sync with the log explorer behavior.
Create visualization flow without MDS enabled:
Create visualization flow with MDS enabled:
Create dashboards flow without MDS enabled:
Create dashboards flow with MDS enabled:
Other issues resolved:
- Remove the redirection link for editing observability-search, observability-visualization and observability-panel based saved-objects with MDS is enabled.
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Remove PPL viz & create observability dashboards in MDS environment

public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, public/components/trace_analytics/home.tsx
Fixes span to logs redireciton, updates mds label when undefined
https://github.com/user-attachments/assets/bc6c1669-2081-4f9d-a11e-a4682b4400f1
=> Fixes span to logs redireciton, updates mds label when undefined

release-notes/opensearch-observability.release-notes-2.18.0.0.md
=> added release-notes for v2.18.0

server/plugin.ts, server/routes/dsl.ts, server/routes/index.ts, server/services/queryService.ts
- Return 503 if opensearch calls failed
- logger usage is added by https://github.com/opensearch-project/dashboards-observability/commit/2ab83698235f958aa28d51465111e3cb996cf4a3#diff-0106d9bfdc6fc208bd6c5ae2c242dd8f479d18dcc51d706df628d973e35fd221R47-R48 but not passed in to QueryService, this PR passes it in
=> [Traces] Return 503 if opensearch calls failed

public/components/integrations/components/create_integration_helpers.ts, server/adaptors/integrations/__test__/builder.test.ts, server/adaptors/integrations/integrations_builder.ts
Fix mds reference update on integration assets
Mds reference was not getting added for integrations there were two issues:
1. The integration builder code was checking the flint source to update the MDS ref.
2. The data ingestion API call wasn't taking MDS ref as parameter. 
https://github.com/user-attachments/assets/bef5ebf7-e6ab-47d0-a548-4361a8e13577
=> Fix mds ref update on integration assets

public/components/notebooks/components/paragraph_components/paragraphs.tsx
Use savedObjects client to fetch notebook visualizations
Notebooks visualizations API was calling the local cluster to fetch savedobjects with MDS enabled. But when the savedObjects are not stored in `.kibana` index, they routes lead to 404/400. Hence, updating the client to use the one provided by OSD core. This automatically takes care of switching between the saved object source. 
https://github.com/user-attachments/assets/5fc25524-8a5a-4886-b5db-f2d0f36553bc
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-or …
=> Use savedObjects client to fetch notebook visualizations

public/components/notebooks/components/paragraph_components/paragraphs.tsx
* Use savedObjects client to fetch notebook visualizations
* resolve comments
---------
(cherry picked from commit 1e52e1de17b999461e572b395572f95f17f4cdef)
=> [Manual Backport 2.x] Use savedObjects client to fetch notebook visualizations (#2241)

common/constants/shared.ts, public/components/common/types.ts, public/components/custom_panels/__tests__/__snapshots__/custom_panel_view.test.tsx.snap, public/components/trace_analytics/components/common/__tests__/helper_functions.test.tsx, public/components/trace_analytics/components/common/helper_functions.tsx, public/components/trace_analytics/home.tsx, public/services/requests/dsl.ts, server/routes/dsl.ts, test/constants.ts
Replace index mapping with field capabilties API for trace filters
1. Fetch field with index mappings wasn't on-boarded to MDS which was leading to 500 connection errors 
2. Fields capabilities API now also works with CCS indices. 
https://github.com/user-attachments/assets/b8d60e41-143d-4e1d-bd93-2df166a7697d
=> Replace index mapping with field caps API for trace filters

.cypress/integration/trace_analytics_test/trace_analytics_dashboard.spec.js, .cypress/integration/trace_analytics_test/trace_analytics_services.spec.js, .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js, .cypress/utils/constants.js, public/components/trace_analytics/components/common/filters/__tests__/__snapshots__/filter_edit_popover.test.tsx.snap, public/components/trace_analytics/components/common/filters/filter_edit_popover.tsx, public/components/trace_analytics/components/common/filters/filter_helpers.tsx, public/components/trace_analytics/components/common/filters/filters.tsx
Updates trace analytics cypress tests
=> [Cypress Updates] Trace analytics updates

.cypress/integration/notebooks_test/notebooks.spec.js, .cypress/utils/constants.js
Update notebooks cypress tests
=> [Cypress Updates] Notebooks updates

.github/workflows/integration-tests-workflow.yml
Separate uploaded cypress artifacts for actions/upload-artifact@v4
Previously the behavior allowed for the artifact names to be the same which resulted in unexpected mutations and accidental corruption. Artifacts created by upload-artifact@v4 are immutable.
This leads to cypress tests failing as artifact upload fails with multiple test groups using the same name to upload. More details can be found here: [uploadArtifactv4/docs](https://github.com/actions/upload-artifact?tab=readme-ov-file#not-uploading-to-the-same-artifact), [Bug report](https://github.com/actions/upload-artifact/issues/478)
Failing PR workflows: https://github.com/opensearch-project/dashboards-observability/actions/runs/11903948018/job/33171873868?pr=2258
By submitting this pull request, I confirm that my contribution is …
=> Separate uploaded cypress artifacts for actions/upload-artifact@v4

.cypress/integration/trace_analytics_test/trace_analytics_services.spec.js, public/components/trace_analytics/components/common/plots/service_dependencies_table.tsx, public/components/trace_analytics/components/services/__tests__/__snapshots__/service_view.test.tsx.snap, public/components/trace_analytics/components/services/service_view.tsx
Fix flaky load of spans table. The CI was acting flaky for load spans table component in the service. The issue was there an incorrect DSL query being sent out to OS to load spans before the DSL state gets updated. The led to the table showing either of the two responses from `incorrect DSL with not filters` or the `correct DSL the time and service filter`. 
https://github.com/opensearch-project/dashboards-observability/issues/1886
Example of CI being flaky: https://github.com/opensearch-project/dashboards-observability/actions/runs/11902220162/job/33170003645 
```
Testing traces Spans table and verify columns functionality
1) Renders the spans table and click on first span to verify details
✓ Render Spans table and verify Column functionality (12352ms)
```
By submitting this pull …
=> Fix flaky render of spans table tests

.cypress/integration/metrics_analytics_test/metrics_analytics.spec.js, .cypress/utils/event_analytics/helpers.js
Update cypress tests for metrics
#1886 
=> [Cypress Updates] Metrics updates

.cypress/integration/app_analytics_test/app_analytics.spec.js, public/components/application_analytics/components/app_table.tsx, public/components/application_analytics/components/application.tsx, public/components/application_analytics/home.tsx, public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap, public/components/custom_panels/panel_modules/visualization_container/visualization_container.tsx
1. Update cypress tests for app analytics 
2. Update to use savedObjects client to delete saved visualizations in applications
3. Add back visualization action menu
Visualization action menu:
#1886 
=> [Cypress Updates] App analytics updates

public/components/notebooks/components/main.tsx, public/components/notebooks/components/notebook.tsx, server/routes/notebooks/paraRouter.ts
Fix notebook routes by removing extra slash. This is only done for new endpoints which use savedObjects API, workspaces and MDS.
* Removes extra slashes from the notebooks saved object routes
* Doesn't need extra tests cypress would validate all the new endpoints automatically
https://github.com/opensearch-project/dashboards-observability/issues/2267 
https://github.com/opensearch-project/dashboards-observability/issues/2262
=> [Bug] Fix notebook routes for savedNotebook endpoints

public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap, public/components/notebooks/components/__tests__/notebook.test.tsx, public/components/notebooks/components/notebook.tsx
Updated notebooks reporting button render
* hides reporting actions button when MDS is enabled. 
=> [Bug] Updated notebooks reporting button render

.cypress/integration/notebooks_test/notebooks.spec.js, .cypress/support/constants.js, .cypress/utils/constants.js, server/services/queryService.ts
Fix SQL/PPL crash with incorrect query
* Notebooks crash when an Incorrect query is added to a paragraph. 
* Added a test to check incorrect query results on PPL and SQL
=> [Bug] Fix SQL/PPL crash with incorrect query

.cypress/integration/event_analytics_test/event_analytics.spec.js, public/components/event_analytics/explorer/events_views/__tests__/__snapshots__/flyout_button.test.tsx.snap, public/components/event_analytics/explorer/events_views/docViewRow.tsx, public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/field.test.tsx.snap, public/components/event_analytics/explorer/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, public/components/event_analytics/explorer/sidebar/field.tsx, public/components/event_analytics/explorer/sidebar/sidebar.tsx
Updates cypress tests for event explorer
#1886 
=> [Cypress Updates] Event explorer updates

.github/workflows/ftr-e2e-dashboards-observability-test.yml
Add step to configure OpenSearch Dashboards before running FTR Cypress tests so that Cypress can connect to server
This will allow the FTR tests to run
=> Configure OpenSearch Dashboards before running in CI

.cypress/integration/app_analytics_test/app_analytics.spec.js, .cypress/integration/event_analytics_test/event_analytics.spec.js, .cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js, .cypress/utils/app_constants.js
Fix flaky cypress tests for app analytics, event analytics, and traces
Change time value to 24 when setting time in applications tests and wait for queries/tables to load before clicking
=> Fix flaky cypress tests

MAINTAINERS.md
Update latest github links in maintainer doc
https://github.com/opensearch-project/dashboards-observability/actions/runs/12637652053/job/35212282695?pr=2299
```
* [404] [https://github.com/vamsi-amazon](https://github.com/vamsi-amazon) | Network error: Not Found
Error: Process completed with exit code 2.
```
=> [Link Checker Fix] Update latest github links in maintainer doc

MAINTAINERS.md
=> [Backport 2.x] Update latest github links in maintainer doc

package.json, yarn.lock
Downgrade cypress version to 12.17.4 to match Opensearch Dashboards 
Observability plugin is failing in dashboards distribution build because of different cypress versions:
```
ERROR [single_version_dependencies] Multiple version ranges for the same dependency
were found declared across different package.json files. Please consolidate
those to match across all package.json files. Different versions for the
same dependency is not supported.
The conflicting dependencies are:
cypress
12.17.4 => opensearch-dashboards
^13.6.0 => observability-dashboards
```
Tests in FTR will continue to fail until it uses distribution build that has observability plugin
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Downgrade cypress to 12.17.4

package.json, yarn.lock
[[CVE-2024-21538](https://github.com/advisories/GHSA-3xgq-45jj-v275)] Bump cross-spawn  to 7.0.5
=> [CVE-2024-21538] Bump cross-spawn to 7.0.5

package.json, yarn.lock
* bump cross-spawn to 7.0.5
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* update yarn.lock
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
---------
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
Co-authored-by: Ritvi Bhatt <ribhatt@amazon.com>
(cherry picked from commit e65749282587b1559c80c682234f069e3763b2d5)
Manual backport for #2322 for 2.19
=> [Backport 2.19] [CVE-2024-21538] Bump cross-spawn to 7.0.5 (#2322)

package.json, yarn.lock
* bump cross-spawn to 7.0.5
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
* update yarn.lock
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
---------
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
Co-authored-by: Ritvi Bhatt <ribhatt@amazon.com>
(cherry picked from commit e65749282587b1559c80c682234f069e3763b2d5)
Manual backport for #2322 
=> [Backport 2.x] [CVE-2024-21538] Bump cross-spawn to 7.0.5 (#2322)

package.json, yarn.lock
Bump nanoid to 3.3.8 for [CVE-2024-55565](https://github.com/advisories/GHSA-mwcw-c2x4-8c55)
=> [CVE-2024-55565] Bump nanoid to 3.3.8

package.json, yarn.lock
Signed-off-by: Ritvi Bhatt <ribhatt@amazon.com>
Co-authored-by: Ritvi Bhatt <ribhatt@amazon.com>
(cherry picked from commit 5cfbba1c630dd6ad9ce3dfd44589fbbde86ad5cf)
=> [Backport 2.19] Bump nanoid to 3.3.8 (#2328)

public/components/trace_analytics/components/traces/span_detail_table.tsx, public/components/trace_analytics/requests/dashboard_request_handler.ts
Add MDS support for missing datasourceId in traceGroup requests. The missing pieces lead to 400 errors when MDS is enabled. This fix makes sure the requests are going to the right cluster as selected by the users. 
=> Add MDS support for missing datasourceId in traceGroup requests

.cypress/integration/trace_analytics_test/trace_analytics_traces.spec.js
[Bug] Remove only from traces cypress spec
A bad commit was introduced in https://github.com/opensearch-project/dashboards-observability/commit/ca79a8f092301c7ae6cf36cd17dda2ca242a910d which led to test skipping and only running one test in the `trace_analytics_traces.spec.js` 
=> [Bug] Remove `only` from traces cypress spec

release-notes/opensearch-observability.release-notes-2.19.0.0.md
Adding release notes for 2.19.0
https://github.com/opensearch-project/dashboards-observability/issues/2234
=> Adding release notes for 2.19.0

public/components/getting_started/getting_started_artifacts/nginx/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/amazon_cloudfront/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/amazon_elb/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/amazon_s3/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/apache/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_cloudtrail/assets/create_mv_cloud-trail-records-1.0.0.sql, server/adaptors/integrations/__data__/repository/aws_waf/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/haproxy/assets/create_mv-1.0.0.sql, server/adaptors/integrations/__data__/repository/nginx/assets/create_mv-1.0.0.sql
Remove `maxFilesPerTrigger` from all the integrations queries
* Relate: https://github.com/opensearch-project/dashboards-observability/issues/2314
=> [Integration] Remove `maxFilesPerTrigger` from all the integrations queries

public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap, public/components/application_analytics/components/flyout_components/trace_detail_render.tsx, public/components/trace_analytics/components/common/constants.tsx, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/span_detail_panel.test.tsx, public/components/trace_analytics/components/traces/span_detail_panel.tsx, public/components/trace_analytics/components/traces/span_detail_table.tsx, public/components/trace_analytics/components/traces/trace_view.tsx, public/components/trace_analytics/components/traces/trace_view_helpers.tsx, public/components/trace_analytics/requests/queries/traces_queries.ts, public/components/trace_analytics/requests/traces_request_handler.ts
With trace optimization PR, we worked on combining multiple queries made for spans in the trace view page. But this meant that all the queries limit themselves to 1000 rather than the earlier limit on spans of 3000 
Secondly, there's an issue when users have a trace with more than 3000 spans, they see random data 3000 spans on the UI. This leads to issues when. users are investigating a trace and want to drill down to a particular span. This PR fixes this issue by reloading the gantt-chart and span table payload when filters are added by the users to narrow down their search. 
https://github.com/user-attachments/assets/ed6940db-fdb8-40f8-8e35-2f2bddf4bac6
#2349 
https://github.com/opensearch-project/dashboards-observability/issues/2334
By submitting this pull request, I confirm that my …
=> Restore spans limit to 3000 in trace view

public/components/application_analytics/__tests__/__snapshots__/flyout.test.tsx.snap, public/components/application_analytics/components/flyout_components/trace_detail_render.tsx, public/components/trace_analytics/components/common/constants.tsx, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/__tests__/__snapshots__/trace_view.test.tsx.snap, public/components/trace_analytics/components/traces/__tests__/span_detail_panel.test.tsx, public/components/trace_analytics/components/traces/span_detail_panel.tsx, public/components/trace_analytics/components/traces/span_detail_table.tsx, public/components/trace_analytics/components/traces/trace_view.tsx, public/components/trace_analytics/components/traces/trace_view_helpers.tsx, public/components/trace_analytics/requests/queries/traces_queries.ts, public/components/trace_analytics/requests/traces_request_handler.ts
* restore spans max value to 3000 in trace view
* update filtering mechanism for span payloads
* avoid parsing again on re-render in trace view
---------
(cherry picked from commit 84fbc2fe1a6809e7f95b4e8d58c32026e8ef4ec8)
PR to main : https://github.com/opensearch-project/dashboards-observability/pull/2353
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/ma …
=> [Backport 2.x]  Restore spans limit to 3000 in trace view

.github/workflows/dashboards-observability-test-and-build-workflow.yml, .github/workflows/ftr-e2e-dashboards-observability-test.yml, .github/workflows/integration-tests-workflow.yml, .github/workflows/verify-binary-install.yml, opensearch_dashboards.json, package.json
Bump dashboards observability to version 3.0.0.0-alpha1
https://github.com/opensearch-project/dashboards-observability/issues/704
=>  Bump dashboards observability to version 3.0.0.0-alpha1

.eslintrc.js, server/adaptors/integrations/__test__/custom_expects.ts, server/adaptors/integrations/__test__/json_repository.test.ts, server/adaptors/integrations/__test__/local_fs_repository.test.ts, server/adaptors/integrations/repository/__test__/integration_reader.test.ts, server/adaptors/integrations/repository/integration_reader.ts
I was debugging some tests locally and it stood out that the errors aren't that useful: most of them are `result.ok` assertions of the form "Expected true but got false." This is inactionable without custom debugging logic (usually well-placed `console.log`s). I've added some result helpers that can check results with context, and show the specific errors on failure. [Failures should be actionable.](https://testing.googleblog.com/2024/05/test-failures-should-be-actionable.html)
After implementing, I tried introducing some random errors in our integration configs and parsing logic, and verified that the failures made sense.
N/A
For more information on following Developer …
=> Improve the test results for Integrations internals

.eslintrc.js, server/adaptors/integrations/__test__/custom_expects.ts, server/adaptors/integrations/__test__/json_repository.test.ts, server/adaptors/integrations/__test__/local_fs_repository.test.ts, server/adaptors/integrations/repository/__test__/integration_reader.test.ts, server/adaptors/integrations/repository/integration_reader.ts
=> [Manual Backport] Backport 2376 to 2.x

common/constants/trace_analytics.ts, common/types/trace_analytics.ts, public/components/event_analytics/explorer/explorer.tsx, public/components/trace_analytics/components/common/__tests__/custom_index_flyout.test.tsx, public/components/trace_analytics/components/common/custom_index_flyout.tsx, public/components/trace_analytics/components/common/helper_functions.tsx, public/components/trace_analytics/components/services/service_view.tsx, public/components/trace_analytics/components/traces/span_detail_flyout.tsx, public/components/trace_analytics/home.tsx, server/plugin_helper/register_settings.ts
Many users of trace analytics have different ways of defining their logs index. Many of them do not want set an alias on their existing indices and fields. Hence, we are adding this experimental feature to enable them to add custom log source used for correlation of spans & services to logs.  
Redirection to Explorer:
https://github.com/user-attachments/assets/2387592b-22a5-4a9b-9c69-81bd9110fa29
Redirection to Discover:
NOTE: We see an error in discover to load data from specific indexes using PPL. This looks to be a discover only issue.
https://github.com/user-attachments/assets/8a17e3d0-a137-4dd9-bd6a-74b4c1095d08
https://github.com/opensearch-project/dashboards-observability/issues/2141
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Support custom logs correlation

package.json, yarn.lock
Bump dep serialize-javascript version to 6.0.2 and @babel/runtime to 7.26.10.
Resolved CVE-2024-11831.
At the moment cypress-parallel maintainer just come back since 2023 and have not release any newer versions yet: https://github.com/tnicola/cypress-parallel/commits/master/
Also bump @babel/runtime to 7.26.10.
as https://www.npmjs.com/package/@nteract/presentational-components havent been updated for a long time.
Related to CVE-2025-27789.
https://github.com/opensearch-project/opensearch-build/issues/3747
- ~~[ ] New functionality includes testing.~~
- ~~[ ] All tests pass, including unit test, integration test and doctest~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] New functionality has javadoc added~~
- ~~[ ] New functionality has user manual doc added~~
By submitting …
=> Bump dep serialize-javascript version to 6.0.2 and @babel/runtime to 7.26.10

.husky/hooks/check-test-only.sh, package.json
Adding husky `.only` check hook to test files 
This PR introduces a pre-commit hook using Husky & lint-staged to prevent committing test files (*.test.js, *.spec.js, *.cy.js, etc.) that contain `.only`. This ensures that no test runs in isolation unintentionally, improving test reliability and preventing CI/CD pipeline issues. 
=> Adding husky `.only` check hook to test files 

README.md
Fix link checker 404 and update the table of content in README
```
* [404] [https://opensearch.org/assets/img/opensearch-logo-themed.svg](https://opensearch.org/assets/img/opensearch-logo-themed.svg) | Network error: Not Found
```
=> Fix link checker 404 and update the table of content in README

server/routes/notebooks/paraRouter.ts
This PR solve the issue where calling the `/api/observability/notebooks/savedNotebook/set_paragraphs` API unable to set paragraphs successfully.
#2416 
1. Open a notebook.
2. Move the position of a paragraph up or down.
3. Refresh the page.
4. Should show the latest paragraphs version.
=> [Bug] Notebooks - fix set_paragraphs API

public/components/trace_analytics/components/common/constants.tsx, public/components/trace_analytics/components/common/shared_components/component_helper_functions.tsx, public/components/trace_analytics/components/common/shared_components/custom_datagrid.tsx, public/components/trace_analytics/components/traces/__tests__/__snapshots__/traces.test.tsx.snap, public/components/trace_analytics/components/traces/traces_content.tsx, public/components/trace_analytics/components/traces/traces_custom_indices_table.tsx, public/components/trace_analytics/components/traces/traces_table.tsx, public/components/trace_analytics/requests/queries/traces_queries.ts, public/components/trace_analytics/requests/traces_request_handler.ts
- Count unique traces using a cardinality aggregation on `traceId`.
- Use the unique trace count values for both `data_prepper` and `custom_data_prepper`.
- Display "warning" in the `data_prepper` view if there are more trace records than are currently shown.
https://github.com/user-attachments/assets/15403ce6-e6be-4a74-bb67-2e3a21060c7c
=> Traces - Add traces unique count based on cardinality aggregation

common/constants/trace_analytics.ts, public/components/trace_analytics/components/common/helper_functions.tsx, public/components/trace_analytics/requests/queries/services_queries.ts, server/plugin_helper/register_settings.ts
The aim of this PR is to make the max nodes and max edges (used in service map related queries) user-configurable, as they are currently (as of 3.1.0) constant values (500 and 1000 respectively), which can result in inaccurate service maps if service map indices contain more than 500 unique services or more than 1000 unique destinations per service.
I've registered these new settings alongside the existing ones:
The default values come from the existing (now deprecated) constants.
The following comparison shows the changes in service map, once the user updates the max node limit (`observability:traceAnalyticsServiceMapMaxNodes`):
- with the default limit of 500:
- with the updated limit of 5: 
The next comparison shows the changes in service map if the user decides to update the maximum …
=> [Traces] Make service map max nodes and max edges values user-configurable
